In [1]:
!pip install neuralforecast --quiet
!pip install statsforecast  --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.0/287.0 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.2/348.2 kB 18.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 831.6/831.6 kB 36.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.8/73.8 MB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 447.2/447.2 kB 35.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.6/46.6 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 62.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires tornado==6.5.1, but you have tornado 6.5.5 which is incompatible.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.6/354.6 kB 14.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.0/281.0 kB 22.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 51.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.9/59.9 kB 5.5 MB/s eta 0:00:00

In [3]:
import time
import pandas as pd
import numpy as np
#from sklearn.preprocessing import LabelEncoder
from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA, SimpleExponentialSmoothingOptimized
from neuralforecast import NeuralForecast
from neuralforecast.models import NBEATS, NHITS, PatchTST
from neuralforecast.auto import AutoNHITS, AutoPatchTST, AutoTimesNet
from utilsforecast.evaluation import evaluate
from utilsforecast.losses import smape, mase, rmsse
from functools import partial
import warnings
warnings.filterwarnings('ignore')

In [4]:
# ----------------------------------------------------------------------
# 1. Загрузка и подготовка данных (как в исходном ноутбуке)
# ----------------------------------------------------------------------
def load_and_preprocess(file_path):
    df = pd.read_excel(file_path)
    df = df.drop_duplicates()
    df["unique_id"] = df["id"].astype(str) + "_" + df["Код филиала"].astype(str) + "_" + df["Код ЦФО"].astype(str)
    df_both = df[df["Показатель"].isin(["ДЗ н.п.", "ДЗ к.п."])]
    id_vars = ["id", "Код филиала", "Код ЦФО", "Показатель", "number", "unique_id"]
    df_long = pd.melt(df_both, id_vars=id_vars, var_name="month", value_name="y")
    def get_date(row):
        month_num = int(row['month'])
        if month_num <= 12:
            year, month = 2022, month_num
        else:
            year, month = 2023, month_num - 12
        if row['Показатель'] == 'ДЗ н.п.':
            return pd.Timestamp(f"{year}-{month:02d}-01")
        else:
            if month == 12:
                next_year, next_month = year + 1, 1
            else:
                next_year, next_month = year, month + 1
            next_month_start = pd.Timestamp(f"{next_year}-{next_month:02d}-01")
            return next_month_start - pd.Timedelta(days=1)
    df_long['ds'] = df_long.apply(get_date, axis=1)
    mask = df_long.groupby("unique_id")["y"].transform("sum") != 0
    df_long = df_long[mask].sort_values(["unique_id", "ds"])
    df_start = df_long[df_long['Показатель'] == 'ДЗ н.п.'].copy()
    df_end = df_long[df_long['Показатель'] == 'ДЗ к.п.'].copy()
    df_end['ds'] = df_end['ds'] + pd.offsets.MonthBegin(1)
    df_combined = pd.concat([df_start, df_end], ignore_index=True)
    df_combined = df_combined.sort_values(['unique_id', 'ds']).drop_duplicates(subset=['unique_id', 'ds'], keep='first')
    return df_combined[['unique_id', 'y', 'ds']]

def classify_time_series(df_long):
    results = []
    for uid, group in df_long.groupby('unique_id'):
        T = len(group)
        non_zero_values = group[group['y'] > 0]['y']
        N = len(non_zero_values)
        adi = T / N if N > 0 else np.inf
        if N == 0:
            cv2 = np.nan
        elif N == 1:
            cv2 = 0.0
        else:
            mean = non_zero_values.mean()
            std = non_zero_values.std(ddof=1)
            cv = std / mean if mean != 0 else np.inf
            cv2 = cv ** 2
        adi_threshold, cv2_threshold = 1.32, 0.49
        if adi <= adi_threshold and cv2 <= cv2_threshold:
            demand_class = "Smooth"
        elif adi <= adi_threshold and cv2 > cv2_threshold:
            demand_class = "Erratic"
        elif adi > adi_threshold and cv2 <= cv2_threshold:
            demand_class = "Intermittent"
        elif adi > adi_threshold and cv2 > cv2_threshold:
            demand_class = "Lumpy"
        else:
            demand_class = "Undefined"
        results.append({'unique_id': uid, 'adi': adi, 'cv2': cv2, 'class': demand_class})
    return pd.DataFrame(results)

def split_train_test(df_long, split_date):
    train = df_long[df_long['ds'] <= split_date].copy()
    test = df_long[df_long['ds'] > split_date].copy()
    return train, test

def filter_by_class(df, classification_df, class_name):
    ids = classification_df[classification_df['class'] == class_name]['unique_id'].values
    return df[df['unique_id'].isin(ids)].copy()

HORIZON = 4
split_date = pd.to_datetime("2023-09-01")

# Загружаем данные
df_long = load_and_preprocess("data.xlsx")
classification_df = classify_time_series(df_long)
train_all, test_all = split_train_test(df_long, split_date)

In [5]:
df_long.head()

    unique_id             y         ds
0  10_1000_14  2.597909e+08 2022-01-01
1  10_1000_14  2.481821e+08 2022-02-01
2  10_1000_14  2.740626e+08 2022-03-01
3  10_1000_14  3.083320e+08 2022-04-01
4  10_1000_14  2.889103e+08 2022-05-01

In [6]:
classification_df['class'].value_counts()

class
Smooth          576
Intermittent    513
Erratic         188
Lumpy           145
Undefined         9
Name: count, dtype: int64

In [7]:
# ----------------------------------------------------------------------
# 2. Базовая модель AutoARIMA (обучение на всех рядах)
# ----------------------------------------------------------------------
def train_autoarima(train_df, test_df, model_name="AutoARIMA"):
    start = time.time()
    sf = StatsForecast(models=[AutoARIMA()], freq='MS', n_jobs=-1)
    forecast = sf.forecast(df=train_df, h=HORIZON)
    forecast = test_df.merge(forecast, on=['unique_id','ds'], how='left')
    train_time = time.time() - start
    return forecast, train_time

baseline_forecast, baseline_time = train_autoarima(train_all, test_all)
print(f"Baseline AutoARIMA обучена за {baseline_time:.2f} сек")

Baseline AutoARIMA обучена за 359.89 сек

In [8]:
# ----------------------------------------------------------------------
# 3. Функция оценки метрик
# ----------------------------------------------------------------------
def evaluate_forecast(forecast_df, train_df, model_col):
    eval_df = evaluate(
        forecast_df[['unique_id','ds','y',model_col]],
        metrics=[smape, partial(mase, seasonality=12), partial(rmsse, seasonality=12)],
        train_df=train_df,
        models=[model_col]
    )
    median_metrics = eval_df.groupby('metric')[model_col].median().to_dict()
    return median_metrics

In [9]:
# ----------------------------------------------------------------------
# 4. Реализация сценариев
# ----------------------------------------------------------------------
# Сценарий 1: двухсегментная схема
# Группа A: Smooth + Erratic -> SimpleExponentialSmoothingOptimized
# Группа B: Intermittent + Lumpy -> AutoARIMA
def scenario1(train_all, test_all, classification_df):
    groupA_ids = classification_df[classification_df['class'].isin(['Smooth','Erratic'])]['unique_id'].values
    groupB_ids = classification_df[classification_df['class'].isin(['Intermittent','Lumpy'])]['unique_id'].values

    trainA = train_all[train_all['unique_id'].isin(groupA_ids)]
    testA = test_all[test_all['unique_id'].isin(groupA_ids)]
    trainB = train_all[train_all['unique_id'].isin(groupB_ids)]
    testB = test_all[test_all['unique_id'].isin(groupB_ids)]

    # Модель для группы A
    startA = time.time()
    modelA = SimpleExponentialSmoothingOptimized()
    sfA = StatsForecast(models=[modelA], freq='MS', n_jobs=-1)
    forecastA = sfA.forecast(df=trainA, h=HORIZON)
    forecastA = testA.merge(forecastA, on=['unique_id','ds'], how='left')
    timeA = time.time() - startA
    # Определяем имя колонки модели
    modelA_name = forecastA.columns[-1]  # последняя колонка после merge

    # Модель для группы B
    startB = time.time()
    modelB = AutoARIMA()
    sfB = StatsForecast(models=[modelB], freq='MS', n_jobs=-1)
    forecastB = sfB.forecast(df=trainB, h=HORIZON)
    forecastB = testB.merge(forecastB, on=['unique_id','ds'], how='left')
    timeB = time.time() - startB
    modelB_name = forecastB.columns[-1]

    # Объединяем
    forecast_all = pd.concat([forecastA, forecastB], ignore_index=True)
    # Создаём единую колонку 'forecast'
    forecast_all['forecast'] = forecast_all[modelA_name].fillna(forecast_all[modelB_name])
    forecast_all = forecast_all[['unique_id','ds','y','forecast']]
    return forecast_all, (timeA, timeB)

# Сценарий 2: полный конвейер (индивидуальные чемпионы)
def scenario2(train_all, test_all, classification_df):
    class_to_model = {
        'Smooth': NBEATS(h=HORIZON, input_size=16, scaler_type='robust', max_steps=500,
                         early_stop_patience_steps=-1, accelerator='auto', random_seed=42),
        'Erratic': AutoPatchTST(h=HORIZON),
        'Intermittent': AutoARIMA(),
        'Lumpy': AutoARIMA()
    }
    forecasts_list = []
    times = {}
    for class_name, model in class_to_model.items():
        train_class = filter_by_class(train_all, classification_df, class_name)
        test_class = filter_by_class(test_all, classification_df, class_name)
        if len(train_class['unique_id'].unique()) == 0:
            continue
        start = time.time()
        if isinstance(model, AutoARIMA):
            sf = StatsForecast(models=[model], freq='MS', n_jobs=-1)
            forecast = sf.forecast(df=train_class, h=HORIZON)
            forecast = test_class.merge(forecast, on=['unique_id','ds'], how='left')
            model_name = forecast.columns[-1]  # динамическое имя
        else:
            nf = NeuralForecast(models=[model], freq='MS')
            nf.fit(df=train_class)
            forecast = nf.predict()
            forecast = test_class.merge(forecast, on=['unique_id','ds'], how='left')
            model_name = forecast.columns[-1]  # динамическое имя
        times[class_name] = time.time() - start
        forecast['forecast'] = forecast[model_name]
        forecasts_list.append(forecast[['unique_id','ds','y','forecast']])
    forecast_all = pd.concat(forecasts_list, ignore_index=True)
    return forecast_all, times

In [10]:
# ----------------------------------------------------------------------
# 5. Запуск сценариев и сбор результатов
# ----------------------------------------------------------------------
print("\n=== Запуск сценариев ===")
# Baseline уже есть
baseline_metrics = evaluate_forecast(baseline_forecast, train_all, 'AutoARIMA')

# Сценарий 1
s1_forecast, s1_times = scenario1(train_all, test_all, classification_df)
s1_metrics = evaluate_forecast(s1_forecast, train_all, 'forecast')
# Время обучения: сумма времени для двух групп
s1_total_time = sum(s1_times)

# Сценарий 2
s2_forecast, s2_times = scenario2(train_all, test_all, classification_df)
s2_metrics = evaluate_forecast(s2_forecast, train_all, 'forecast')
s2_total_time = sum(s2_times.values())

=== Запуск сценариев ===

INFO:lightning_fabric.utilities.seed:Seed set to 42
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name         | Type          | Params | Mode
-------------------------------------------------------
0 | loss         | MAE           | 0      | train
1 | padder_train | ConstantPad1d | 0      | train
2 | scaler       | TemporalNorm  | 0      | train
3 | blocks       | ModuleList    | 2.4 M  | train
-------------------------------------------------------
2.4 M     Trainable params
180       Non-trainable params
2.4 M     Total params
9.639     Total estimated model params size (MB)
31        Modules in train mode
0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=500` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

2026-05-21 09:24:58,296	INFO worker.py:2012 -- Started a local Ray instance.
2026-05-21 09:25:02,799	INFO tune.py:253 -- Initializing Ray automatically. For cluster usage or custom Ray initialization, call `ray.init(...)` before `Tuner(...)`.

+--------------------------------------------------------------------+
| Configuration for experiment     _train_tune_2026-05-21_09-24-47   |
+--------------------------------------------------------------------+
| Search algorithm                 BasicVariantGenerator             |
| Scheduler                        FIFOScheduler                     |
| Number of trials                 10                                |
+--------------------------------------------------------------------+

View detailed results here: /root/ray_results/_train_tune_2026-05-21_09-24-47
To visualize your results with TensorBoard, run: `tensorboard --logdir /tmp/ray/session_2026-05-21_09-24-47_705775_1408/artifacts/2026-05-21_09-25-02/_train_tune_2026-05-21_09-24-47/driver_artifacts`

(_train_tune pid=5236) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=5236) Seed set to 17
(_train_tune pid=5236) GPU available: True (cuda), used: True
(_train_tune pid=5236) TPU available: False, using: 0 TPU cores
(_train_tune pid=5236) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=5236)
(_train_tune pid=5236)   | Name         | Type              | Params | Mode
(_train_tune pid=5236) -----------------------------------------------------------
(_train_tune pid=5236) 0 | loss         | MAE               | 0      | train
(_train_tune pid=5236) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=5236) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=5236) 3 | model        | PatchTST_backbone | 400 K  | train
(_train_tune pid=5236) -----------------------------------------------------------
(_train_tune pid=5236) 400 K     Trainable params
(_train_tune pid=5236) 3         Non-trainable params
(_train_tune pid=5236) 400 K     Total params
(_train_tune pid=5236) 1.601     Total estimated model params size (MB)
(_train_tune pid=5236) 90        Modules in train mode
(_train_tune pid=5236) 0         Modules in eval mode
(_train_tune pid=5236) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/6 [00:00<?, ?it/s]
Epoch 1:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=902.0, train_loss_epoch=792.0]
Epoch 2:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.94e+3, train_loss_epoch=840.0]
Epoch 3:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=21.50, train_loss_epoch=858.0]
Epoch 4:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.950, train_loss_epoch=893.0]
Epoch 6:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=801.0, train_loss_epoch=852.0]
Epoch 7:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.66e+3, train_loss_epoch=982.0]
Epoch 8:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=97.20, train_loss_epoch=735.0]
Epoch 9:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.51e+3, train_loss_epoch=829.0]
Epoch 10:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=845.0, train_loss_epoch=913.0]
Epoch 11:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.49e+3, train_loss_epoch=804.0]
Epoch 12:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=715.0, train_loss_epoch=724.0]
Epoch 13:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.610, train_loss_epoch=908.0]
Epoch 14:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.37e+3, train_loss_epoch=1.04e+3]
Epoch 15:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.520, train_loss_epoch=811.0]
Epoch 16:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=875.0, train_loss_epoch=764.0]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
(_train_tune pid=5236)
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 154.20it/s]
Epoch 17:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.4e+3, train_loss_epoch=740.0, valid_loss=2.13e+7]
Epoch 18:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.94e+3, train_loss_epoch=1.15e+3, valid_loss=2.13e+7]
Epoch 19:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=6.720, train_loss_epoch=860.0, valid_loss=2.13e+7]
Epoch 20:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.860, train_loss_epoch=822.0, valid_loss=2.13e+7]
Epoch 21:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=940.0, train_loss_epoch=698.0, valid_loss=2.13e+7]
Epoch 22:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.91e+3, train_loss_epoch=940.0, valid_loss=2.13e+7]
Epoch 23:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.58e+3, train_loss_epoch=1.22e+3, valid_loss=2.13e+7]
Epoch 24:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=174.0, train_loss_epoch=579.0, valid_loss=2.13e+7]
Epoch 25:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=803.0, train_loss_epoch=848.0, valid_loss=2.13e+7]
Epoch 26:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=615.0, train_loss_epoch=824.0, valid_loss=2.13e+7]
Epoch 27:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=21.90, train_loss_epoch=889.0, valid_loss=2.13e+7]
Epoch 28:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.85e+3, train_loss_epoch=684.0, valid_loss=2.13e+7]
Epoch 29:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=108.0, train_loss_epoch=699.0, valid_loss=2.13e+7]
Epoch 30:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.410, train_loss_epoch=685.0, valid_loss=2.13e+7]
Epoch 31:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=71.90, train_loss_epoch=749.0, valid_loss=2.13e+7]
Epoch 32:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.06e+3, train_loss_epoch=654.0, valid_loss=2.13e+7]
Epoch 33:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=10.10, train_loss_epoch=744.0, valid_loss=2.13e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
(_train_tune pid=5236)
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 134.64it/s]
(_train_tune pid=5236)
Epoch 34:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=508.0, train_loss_epoch=730.0, valid_loss=2.14e+7]
Epoch 35:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=184.0, train_loss_epoch=806.0, valid_loss=2.14e+7]
Epoch 36:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=10.50, train_loss_epoch=885.0, valid_loss=2.14e+7]
Epoch 37:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=617.0, train_loss_epoch=879.0, valid_loss=2.14e+7]
Epoch 37: 100%|██████████| 6/6 [00:00<00:00, 47.91it/s, v_num=0, train_loss_step=2.330, train_loss_epoch=804.0, valid_loss=2.14e+7]
Epoch 38:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.330, train_loss_epoch=804.0, valid_loss=2.14e+7]
Epoch 39:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=735.0, train_loss_epoch=857.0, valid_loss=2.14e+7]
Epoch 40:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=749.0, train_loss_epoch=549.0, valid_loss=2.14e+7]
Epoch 41:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=24.90, train_loss_epoch=842.0, valid_loss=2.14e+7]
Epoch 42:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=6.100, train_loss_epoch=655.0, valid_loss=2.14e+7]
Epoch 43:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.680, train_loss_epoch=842.0, valid_loss=2.14e+7]
Epoch 44:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.48e+3, train_loss_epoch=1.15e+3, valid_loss=2.14e+7]
Epoch 45:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.490, train_loss_epoch=866.0, valid_loss=2.14e+7]
Epoch 46:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.65e+3, train_loss_epoch=959.0, valid_loss=2.14e+7]
Epoch 47:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=515.0, train_loss_epoch=885.0, valid_loss=2.14e+7]
Epoch 48:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=515.0, train_loss_epoch=885.0, valid_loss=2.14e+7]
Epoch 49:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.84e+3, train_loss_epoch=1.06e+3, valid_loss=2.14e+7]
Epoch 49: 100%|██████████| 6/6 [00:00<00:00, 66.10it/s, v_num=0, train_loss_step=7.220, train_loss_epoch=1.06e+3, valid_loss=2.14e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
(_train_tune pid=5236)
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 129.60it/s]
Epoch 50:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=7.220, train_loss_epoch=760.0, valid_loss=2.14e+7]
Epoch 51:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=18.00, train_loss_epoch=836.0, valid_loss=2.14e+7]
Epoch 52:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=741.0, train_loss_epoch=803.0, valid_loss=2.14e+7]
Epoch 53:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.640, train_loss_epoch=870.0, valid_loss=2.14e+7]
Epoch 54:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=89.90, train_loss_epoch=710.0, valid_loss=2.14e+7]
Epoch 55:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.53e+3, train_loss_epoch=1.11e+3, valid_loss=2.14e+7]
Epoch 56:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=12.00, train_loss_epoch=849.0, valid_loss=2.14e+7]
Epoch 57:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.44e+3, train_loss_epoch=793.0, valid_loss=2.14e+7]
Epoch 58:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=901.0, train_loss_epoch=955.0, valid_loss=2.14e+7]
Epoch 59:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.69e+3, train_loss_epoch=1.01e+3, valid_loss=2.14e+7]
Epoch 61:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.5e+3, train_loss_epoch=1.05e+3, valid_loss=2.14e+7]
Epoch 62:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=604.0, train_loss_epoch=837.0, valid_loss=2.14e+7]
Epoch 63:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=18.60, train_loss_epoch=844.0, valid_loss=2.14e+7]
Epoch 64:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=11.20, train_loss_epoch=667.0, valid_loss=2.14e+7]
Epoch 65:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=486.0, train_loss_epoch=838.0, valid_loss=2.14e+7]
Epoch 66:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=55.80, train_loss_epoch=837.0, valid_loss=2.14e+7]
(_train_tune pid=5236)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 169.66it/s]
Epoch 66:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=912.0, train_loss_epoch=733.0, valid_loss=2.13e+7]
Epoch 67:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=912.0, train_loss_epoch=733.0, valid_loss=2.13e+7]
Epoch 68:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=263.0, train_loss_epoch=676.0, valid_loss=2.13e+7]
Epoch 69:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=8.170, train_loss_epoch=762.0, valid_loss=2.13e+7]
Epoch 70:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.24e+3, train_loss_epoch=952.0, valid_loss=2.13e+7]
Epoch 71:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=942.0, train_loss_epoch=910.0, valid_loss=2.13e+7]
Epoch 72:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=768.0, train_loss_epoch=822.0, valid_loss=2.13e+7]
Epoch 73:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=6.180, train_loss_epoch=600.0, valid_loss=2.13e+7]
Epoch 74:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.8e+3, train_loss_epoch=972.0, valid_loss=2.13e+7]
Epoch 75:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.54e+3, train_loss_epoch=1.13e+3, valid_loss=2.13e+7]
Epoch 76:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.740, train_loss_epoch=629.0, valid_loss=2.13e+7]
Epoch 77:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=493.0, train_loss_epoch=761.0, valid_loss=2.13e+7]
Epoch 78:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.84e+3, train_loss_epoch=1.05e+3, valid_loss=2.13e+7]
Epoch 79:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=939.0, train_loss_epoch=854.0, valid_loss=2.13e+7]
Epoch 80:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.7e+3, train_loss_epoch=769.0, valid_loss=2.13e+7]
Epoch 81:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=29.30, train_loss_epoch=892.0, valid_loss=2.13e+7]
Epoch 82:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=12.40, train_loss_epoch=878.0, valid_loss=2.13e+7]
Epoch 83:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=35.10, train_loss_epoch=856.0, valid_loss=2.13e+7]
(_train_tune pid=5236)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 137.12it/s]
Epoch 83:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=829.0, train_loss_epoch=856.0, valid_loss=2.12e+7]
Epoch 84:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=7.150, train_loss_epoch=619.0, valid_loss=2.12e+7]
Epoch 85: 100%|██████████| 6/6 [00:00<00:00, 68.55it/s, v_num=0, train_loss_step=2.23e+3, train_loss_epoch=948.0, valid_loss=2.12e+7]
Epoch 85: 100%|██████████| 6/6 [00:00<00:00, 65.84it/s, v_num=0, train_loss_step=737.0, train_loss_epoch=948.0, valid_loss=2.12e+7]
Epoch 86:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=737.0, train_loss_epoch=743.0, valid_loss=2.12e+7]
Epoch 87:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=317.0, train_loss_epoch=666.0, valid_loss=2.12e+7]
Epoch 88:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.09e+3, train_loss_epoch=1.14e+3, valid_loss=2.12e+7]
Epoch 89:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=6.240, train_loss_epoch=852.0, valid_loss=2.12e+7]
Epoch 90:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=5.070, train_loss_epoch=617.0, valid_loss=2.12e+7]
Epoch 91:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.630, train_loss_epoch=814.0, valid_loss=2.12e+7]
Epoch 92:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.14e+3, train_loss_epoch=879.0, valid_loss=2.12e+7]
Epoch 93:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=811.0, train_loss_epoch=707.0, valid_loss=2.12e+7]
Epoch 94:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=65.50, train_loss_epoch=729.0, valid_loss=2.12e+7]
Epoch 95:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=396.0, train_loss_epoch=746.0, valid_loss=2.12e+7]
Epoch 96:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.04e+3, train_loss_epoch=862.0, valid_loss=2.12e+7]
Epoch 97:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=163.0, train_loss_epoch=845.0, valid_loss=2.12e+7]
Epoch 98:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=336.0, train_loss_epoch=919.0, valid_loss=2.12e+7]
Epoch 99:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.92e+3, train_loss_epoch=905.0, valid_loss=2.12e+7]
Epoch 99: 100%|██████████| 6/6 [00:00<00:00, 62.23it/s, v_num=0, train_loss_step=1.32e+3, train_loss_epoch=905.0, valid_loss=2.12e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 162.17it/s]
Epoch 100:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.32e+3, train_loss_epoch=853.0, valid_loss=2.14e+7]
Epoch 101:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=199.0, train_loss_epoch=680.0, valid_loss=2.14e+7]
Epoch 102:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=992.0, train_loss_epoch=783.0, valid_loss=2.14e+7]
Epoch 103:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=265.0, train_loss_epoch=793.0, valid_loss=2.14e+7]
Epoch 104:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=703.0, train_loss_epoch=622.0, valid_loss=2.14e+7]
Epoch 105:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=536.0, train_loss_epoch=865.0, valid_loss=2.14e+7]
Epoch 106:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=356.0, train_loss_epoch=842.0, valid_loss=2.14e+7]
Epoch 107:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=104.0, train_loss_epoch=821.0, valid_loss=2.14e+7]
Epoch 108:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=496.0, train_loss_epoch=723.0, valid_loss=2.14e+7]
Epoch 109:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=5.160, train_loss_epoch=823.0, valid_loss=2.14e+7]
Epoch 110:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.260, train_loss_epoch=782.0, valid_loss=2.14e+7]
Epoch 112:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.120, train_loss_epoch=769.0, valid_loss=2.14e+7]
Epoch 113:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=969.0, train_loss_epoch=874.0, valid_loss=2.14e+7]
Epoch 114:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.060, train_loss_epoch=838.0, valid_loss=2.14e+7]
Epoch 115:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.46e+3, train_loss_epoch=983.0, valid_loss=2.14e+7]
Epoch 116:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=219.0, train_loss_epoch=627.0, valid_loss=2.14e+7]
(_train_tune pid=5236)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 173.37it/s]
Epoch 116:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=323.0, train_loss_epoch=627.0, valid_loss=2.17e+7]
Epoch 118:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=257.0, train_loss_epoch=765.0, valid_loss=2.17e+7]
Epoch 119:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=970.0, train_loss_epoch=826.0, valid_loss=2.17e+7]
Epoch 120:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=20.90, train_loss_epoch=909.0, valid_loss=2.17e+7]
Epoch 121:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=10.90, train_loss_epoch=841.0, valid_loss=2.17e+7]
Epoch 122:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=93.80, train_loss_epoch=898.0, valid_loss=2.17e+7]
Epoch 123:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.050, train_loss_epoch=790.0, valid_loss=2.17e+7]
Epoch 124:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=344.0, train_loss_epoch=830.0, valid_loss=2.17e+7]
Epoch 125:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.27e+3, train_loss_epoch=978.0, valid_loss=2.17e+7]
Epoch 126:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.08e+3, train_loss_epoch=807.0, valid_loss=2.17e+7]
Epoch 127:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.65e+3, train_loss_epoch=873.0, valid_loss=2.17e+7]
Epoch 128:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.11e+3, train_loss_epoch=1.18e+3, valid_loss=2.17e+7]
Epoch 129:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.180, train_loss_epoch=808.0, valid_loss=2.17e+7]
Epoch 131:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=827.0, train_loss_epoch=949.0, valid_loss=2.17e+7]
Epoch 132:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=742.0, train_loss_epoch=906.0, valid_loss=2.17e+7]
Epoch 133:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=41.50, train_loss_epoch=847.0, valid_loss=2.17e+7]
(_train_tune pid=5236)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 164.80it/s]
Epoch 133:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.22e+3, train_loss_epoch=847.0, valid_loss=2.12e+7]
Epoch 134:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=935.0, train_loss_epoch=750.0, valid_loss=2.12e+7]
Epoch 135:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=6.800, train_loss_epoch=871.0, valid_loss=2.12e+7]
Epoch 136:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=167.0, train_loss_epoch=778.0, valid_loss=2.12e+7]
Epoch 138:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.17e+3, train_loss_epoch=898.0, valid_loss=2.12e+7]
Epoch 139:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.41e+3, train_loss_epoch=769.0, valid_loss=2.12e+7]
Epoch 140:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=177.0, train_loss_epoch=839.0, valid_loss=2.12e+7]
Epoch 141:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.68e+3, train_loss_epoch=934.0, valid_loss=2.12e+7]
Epoch 143:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=674.0, train_loss_epoch=838.0, valid_loss=2.12e+7]
Epoch 144:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.92e+3, train_loss_epoch=885.0, valid_loss=2.12e+7]

(_train_tune pid=5236) `Trainer.fit` stopped: `max_steps=5000` reached.
(_train_tune pid=5763) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=5763) Seed set to 11
(_train_tune pid=5763) GPU available: True (cuda), used: True
(_train_tune pid=5763) TPU available: False, using: 0 TPU cores
(_train_tune pid=5763) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=5763)
(_train_tune pid=5763)   | Name         | Type              | Params | Mode
(_train_tune pid=5763) -----------------------------------------------------------
(_train_tune pid=5763) 0 | loss         | MAE               | 0      | train
(_train_tune pid=5763) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=5763) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=5763) 3 | model        | PatchTST_backbone | 1.2 M  | train
(_train_tune pid=5763) -----------------------------------------------------------
(_train_tune pid=5763) 1.2 M     Trainable params
(_train_tune pid=5763) 3         Non-trainable params
(_train_tune pid=5763) 1.2 M     Total params
(_train_tune pid=5763) 4.772     Total estimated model params size (MB)
(_train_tune pid=5763) 89        Modules in train mode
(_train_tune pid=5763) 0         Modules in eval mode
(_train_tune pid=5763) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 1:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.63e+7, train_loss_epoch=1.63e+7]
Epoch 6:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.36e+7, train_loss_epoch=3.36e+7]
Epoch 11:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.96e+7, train_loss_epoch=2.96e+7]
Epoch 16:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.38e+7, train_loss_epoch=3.38e+7]
Epoch 21:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.4e+7, train_loss_epoch=2.4e+7]
Epoch 26: 100%|██████████| 1/1 [00:00<00:00, 49.80it/s, v_num=0, train_loss_step=2.74e+7, train_loss_epoch=2.33e+7]
Epoch 27:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.74e+7, train_loss_epoch=2.74e+7]
Epoch 32:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.47e+7, train_loss_epoch=2.47e+7]
Epoch 36:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.23e+7, train_loss_epoch=2.23e+7]
Epoch 41:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.59e+7, train_loss_epoch=2.59e+7]
Epoch 46:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.09e+7, train_loss_epoch=2.09e+7]
Epoch 51: 100%|██████████| 1/1 [00:00<00:00, 57.71it/s, v_num=0, train_loss_step=3.01e+7, train_loss_epoch=2.27e+7]
Epoch 51: 100%|██████████| 1/1 [00:00<00:00, 55.38it/s, v_num=0, train_loss_step=3.01e+7, train_loss_epoch=3.01e+7]
Epoch 52:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.01e+7, train_loss_epoch=3.01e+7]
Epoch 57:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.53e+7, train_loss_epoch=2.53e+7]
Epoch 62:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.09e+7, train_loss_epoch=2.09e+7]
Epoch 67:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.66e+7, train_loss_epoch=3.66e+7]
Epoch 72:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.8e+7, train_loss_epoch=2.8e+7]
Epoch 72: 100%|██████████| 1/1 [00:00<00:00, 52.96it/s, v_num=0, train_loss_step=2.51e+7, train_loss_epoch=2.8e+7]
Epoch 73:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.51e+7, train_loss_epoch=2.51e+7]
Epoch 78:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.26e+7, train_loss_epoch=2.26e+7]
Epoch 83:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.27e+7, train_loss_epoch=3.27e+7]
Epoch 87: 100%|██████████| 1/1 [00:00<00:00, 50.89it/s, v_num=0, train_loss_step=3.82e+7, train_loss_epoch=3.82e+7]
Epoch 88:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.82e+7, train_loss_epoch=3.82e+7]
Epoch 93:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.62e+7, train_loss_epoch=3.62e+7]
Epoch 98:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.8e+7, train_loss_epoch=2.8e+7]
Epoch 99: 100%|██████████| 1/1 [00:00<00:00, 53.99it/s, v_num=0, train_loss_step=2.78e+7, train_loss_epoch=1.87e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 191.91it/s]
Epoch 102:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.33e+7, train_loss_epoch=2.33e+7, valid_loss=3.11e+7]
Epoch 107: 100%|██████████| 1/1 [00:00<00:00, 55.99it/s, v_num=0, train_loss_step=1.68e+7, train_loss_epoch=2.68e+7, valid_loss=3.11e+7]
Epoch 107: 100%|██████████| 1/1 [00:00<00:00, 54.09it/s, v_num=0, train_loss_step=1.68e+7, train_loss_epoch=1.68e+7, valid_loss=3.11e+7]
Epoch 108:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.68e+7, train_loss_epoch=1.68e+7, valid_loss=3.11e+7]
Epoch 113: 100%|██████████| 1/1 [00:00<00:00, 58.98it/s, v_num=0, train_loss_step=3.56e+7, train_loss_epoch=3.56e+7, valid_loss=3.11e+7]
Epoch 114:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.56e+7, train_loss_epoch=3.56e+7, valid_loss=3.11e+7]
Epoch 119:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.39e+7, train_loss_epoch=2.39e+7, valid_loss=3.11e+7]
Epoch 125:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.93e+7, train_loss_epoch=2.93e+7, valid_loss=3.11e+7]
Epoch 125: 100%|██████████| 1/1 [00:00<00:00, 62.04it/s, v_num=0, train_loss_step=2.01e+7, train_loss_epoch=2.93e+7, valid_loss=3.11e+7]
Epoch 126:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.01e+7, train_loss_epoch=2.01e+7, valid_loss=3.11e+7]
Epoch 131:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.86e+7, train_loss_epoch=1.86e+7, valid_loss=3.11e+7]
Epoch 131:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.43e+7, train_loss_epoch=2.43e+7, valid_loss=3.11e+7]
Epoch 132:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.43e+7, train_loss_epoch=2.43e+7, valid_loss=3.11e+7]
Epoch 137:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.97e+7, train_loss_epoch=1.97e+7, valid_loss=3.11e+7]
Epoch 143:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.57e+7, train_loss_epoch=2.57e+7, valid_loss=3.11e+7]
Epoch 148:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.21e+7, train_loss_epoch=2.21e+7, valid_loss=3.11e+7]
Epoch 153:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.99e+7, train_loss_epoch=2.99e+7, valid_loss=3.11e+7]
Epoch 158:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.64e+7, train_loss_epoch=2.64e+7, valid_loss=3.11e+7]
Epoch 163: 100%|██████████| 1/1 [00:00<00:00, 52.61it/s, v_num=0, train_loss_step=2.37e+7, train_loss_epoch=3.58e+7, valid_loss=3.11e+7]
Epoch 164:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.37e+7, train_loss_epoch=2.37e+7, valid_loss=3.11e+7]
Epoch 169:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.08e+7, train_loss_epoch=2.08e+7, valid_loss=3.11e+7]
Epoch 174:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.47e+7, train_loss_epoch=2.47e+7, valid_loss=3.11e+7]
Epoch 179:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.03e+7, train_loss_epoch=3.03e+7, valid_loss=3.11e+7]
Epoch 179: 100%|██████████| 1/1 [00:00<00:00, 53.12it/s, v_num=0, train_loss_step=2.7e+7, train_loss_epoch=2.7e+7, valid_loss=3.11e+7]
Epoch 180:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.7e+7, train_loss_epoch=2.7e+7, valid_loss=3.11e+7]
Epoch 185:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.38e+7, train_loss_epoch=2.38e+7, valid_loss=3.11e+7]
Epoch 189:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.94e+7, train_loss_epoch=2.94e+7, valid_loss=3.11e+7]
Epoch 189: 100%|██████████| 1/1 [00:00<00:00, 37.37it/s, v_num=0, train_loss_step=2.57e+7, train_loss_epoch=2.57e+7, valid_loss=3.11e+7]
Epoch 190:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.57e+7, train_loss_epoch=2.57e+7, valid_loss=3.11e+7]
Epoch 194: 100%|██████████| 1/1 [00:00<00:00, 44.04it/s, v_num=0, train_loss_step=3.23e+7, train_loss_epoch=3.23e+7, valid_loss=3.11e+7]
Epoch 199: 100%|██████████| 1/1 [00:00<00:00, 54.84it/s, v_num=0, train_loss_step=2.6e+7, train_loss_epoch=2.15e+7, valid_loss=3.11e+7]
(_train_tune pid=5763)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 180.01it/s]
Epoch 204:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.73e+7, train_loss_epoch=1.73e+7, valid_loss=3.11e+7]
Epoch 210:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.34e+7, train_loss_epoch=3.34e+7, valid_loss=3.11e+7]
Epoch 215:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.54e+7, train_loss_epoch=2.54e+7, valid_loss=3.11e+7]
Epoch 221:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.2e+7, train_loss_epoch=3.2e+7, valid_loss=3.11e+7]
Epoch 226:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.07e+7, train_loss_epoch=2.07e+7, valid_loss=3.11e+7]
Epoch 231:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.51e+7, train_loss_epoch=2.51e+7, valid_loss=3.11e+7]
Epoch 236:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.27e+7, train_loss_epoch=2.27e+7, valid_loss=3.11e+7]
Epoch 237:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.17e+7, train_loss_epoch=2.17e+7, valid_loss=3.11e+7]
Epoch 241:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.14e+7, train_loss_epoch=2.14e+7, valid_loss=3.11e+7]
Epoch 246:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.11e+7, train_loss_epoch=3.11e+7, valid_loss=3.11e+7]
Epoch 251:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.4e+7, train_loss_epoch=2.4e+7, valid_loss=3.11e+7]
Epoch 256:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.3e+7, train_loss_epoch=2.3e+7, valid_loss=3.11e+7]
Epoch 261:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.97e+7, train_loss_epoch=2.97e+7, valid_loss=3.11e+7]
Epoch 266:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.41e+7, train_loss_epoch=2.41e+7, valid_loss=3.11e+7]
Epoch 271:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.79e+7, train_loss_epoch=2.79e+7, valid_loss=3.11e+7]
Epoch 276:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.4e+7, train_loss_epoch=2.4e+7, valid_loss=3.11e+7]
Epoch 281:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.82e+7, train_loss_epoch=2.82e+7, valid_loss=3.11e+7]
Epoch 286:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.85e+7, train_loss_epoch=2.85e+7, valid_loss=3.11e+7]
Epoch 290:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.86e+7, train_loss_epoch=1.86e+7, valid_loss=3.11e+7]
Epoch 295:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.72e+7, train_loss_epoch=2.72e+7, valid_loss=3.11e+7]
Epoch 299: 100%|██████████| 1/1 [00:00<00:00, 53.99it/s, v_num=0, train_loss_step=3e+7, train_loss_epoch=2.1e+7, valid_loss=3.11e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
(_train_tune pid=5763)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 174.82it/s]
Epoch 303: 100%|██████████| 1/1 [00:00<00:00, 50.88it/s, v_num=0, train_loss_step=2.27e+7, train_loss_epoch=2.82e+7, valid_loss=3.11e+7]
Epoch 304:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.27e+7, train_loss_epoch=2.27e+7, valid_loss=3.11e+7]
Epoch 309:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.75e+7, train_loss_epoch=2.75e+7, valid_loss=3.11e+7]
Epoch 313:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.09e+7, train_loss_epoch=3.09e+7, valid_loss=3.11e+7]
Epoch 319:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.18e+7, train_loss_epoch=2.18e+7, valid_loss=3.11e+7]
Epoch 324:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.53e+7, train_loss_epoch=2.53e+7, valid_loss=3.11e+7]
Epoch 329:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.12e+7, train_loss_epoch=2.12e+7, valid_loss=3.11e+7]
Epoch 334:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.21e+7, train_loss_epoch=2.21e+7, valid_loss=3.11e+7]
Epoch 338:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.64e+7, train_loss_epoch=2.64e+7, valid_loss=3.11e+7]
Epoch 343:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.08e+7, train_loss_epoch=4.08e+7, valid_loss=3.11e+7]
Epoch 347: 100%|██████████| 1/1 [00:00<00:00, 50.06it/s, v_num=0, train_loss_step=1.82e+7, train_loss_epoch=2.77e+7, valid_loss=3.11e+7]
Epoch 347: 100%|██████████| 1/1 [00:00<00:00, 48.27it/s, v_num=0, train_loss_step=1.82e+7, train_loss_epoch=1.82e+7, valid_loss=3.11e+7]
Epoch 348:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.82e+7, train_loss_epoch=1.82e+7, valid_loss=3.11e+7]
Epoch 352:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.34e+7, train_loss_epoch=2.34e+7, valid_loss=3.11e+7]
Epoch 357:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.64e+7, train_loss_epoch=3.64e+7, valid_loss=3.11e+7]
Epoch 362:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.82e+7, train_loss_epoch=1.82e+7, valid_loss=3.11e+7]
Epoch 367:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.14e+7, train_loss_epoch=3.14e+7, valid_loss=3.11e+7]
Epoch 371: 100%|██████████| 1/1 [00:00<00:00, 45.97it/s, v_num=0, train_loss_step=2.77e+7, train_loss_epoch=2.77e+7, valid_loss=3.11e+7]
Epoch 372:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.77e+7, train_loss_epoch=2.77e+7, valid_loss=3.11e+7]
Epoch 377:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.39e+7, train_loss_epoch=2.39e+7, valid_loss=3.11e+7]
Epoch 382:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.06e+7, train_loss_epoch=3.06e+7, valid_loss=3.11e+7]
Epoch 386:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.13e+7, train_loss_epoch=3.13e+7, valid_loss=3.11e+7]
Epoch 391:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.39e+7, train_loss_epoch=2.39e+7, valid_loss=3.11e+7]
Epoch 396:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.86e+7, train_loss_epoch=2.86e+7, valid_loss=3.11e+7]
Epoch 399: 100%|██████████| 1/1 [00:00<00:00, 56.11it/s, v_num=0, train_loss_step=2.21e+7, train_loss_epoch=1.91e+7, valid_loss=3.11e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 176.50it/s]
Epoch 400:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.21e+7, train_loss_epoch=2.21e+7, valid_loss=3.11e+7]
Epoch 405: 100%|██████████| 1/1 [00:00<00:00, 59.35it/s, v_num=0, train_loss_step=2.48e+7, train_loss_epoch=1.78e+7, valid_loss=3.11e+7]
Epoch 405: 100%|██████████| 1/1 [00:00<00:00, 57.19it/s, v_num=0, train_loss_step=2.48e+7, train_loss_epoch=2.48e+7, valid_loss=3.11e+7]
Epoch 406:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.48e+7, train_loss_epoch=2.48e+7, valid_loss=3.11e+7]
Epoch 411:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.37e+7, train_loss_epoch=2.37e+7, valid_loss=3.11e+7]
Epoch 416:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.47e+7, train_loss_epoch=2.47e+7, valid_loss=3.11e+7]
Epoch 422:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.19e+7, train_loss_epoch=3.19e+7, valid_loss=3.11e+7]
Epoch 427:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.74e+7, train_loss_epoch=2.74e+7, valid_loss=3.11e+7]
Epoch 432:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.5e+7, train_loss_epoch=3.5e+7, valid_loss=3.11e+7]
Epoch 436:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.52e+7, train_loss_epoch=2.52e+7, valid_loss=3.11e+7]
Epoch 441:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.64e+7, train_loss_epoch=2.64e+7, valid_loss=3.11e+7]
Epoch 446:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.66e+7, train_loss_epoch=2.66e+7, valid_loss=3.11e+7]
Epoch 449:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.14e+7, train_loss_epoch=3.14e+7, valid_loss=3.11e+7]
Epoch 453:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.34e+7, train_loss_epoch=2.34e+7, valid_loss=3.11e+7]
Epoch 456: 100%|██████████| 1/1 [00:00<00:00, 34.61it/s, v_num=0, train_loss_step=2.12e+7, train_loss_epoch=2.59e+7, valid_loss=3.11e+7]
Epoch 460:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.41e+7, train_loss_epoch=2.41e+7, valid_loss=3.11e+7]
Epoch 464:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.58e+7, train_loss_epoch=2.58e+7, valid_loss=3.11e+7]
Epoch 468:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.75e+7, train_loss_epoch=1.75e+7, valid_loss=3.11e+7]
Epoch 472:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.35e+7, train_loss_epoch=2.35e+7, valid_loss=3.11e+7]
Epoch 475:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.29e+7, train_loss_epoch=3.29e+7, valid_loss=3.11e+7]
Epoch 479:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.05e+7, train_loss_epoch=2.05e+7, valid_loss=3.11e+7]
Epoch 482:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.71e+7, train_loss_epoch=1.71e+7, valid_loss=3.11e+7]
Epoch 486:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.46e+7, train_loss_epoch=3.46e+7, valid_loss=3.11e+7]
Epoch 490:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.87e+7, train_loss_epoch=2.87e+7, valid_loss=3.11e+7]
Epoch 494:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.87e+7, train_loss_epoch=2.87e+7, valid_loss=3.11e+7]
Epoch 497:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.27e+7, train_loss_epoch=3.27e+7, valid_loss=3.11e+7]
Epoch 499: 100%|██████████| 1/1 [00:00<00:00, 49.06it/s, v_num=0, train_loss_step=2.11e+7, train_loss_epoch=3.01e+7, valid_loss=3.11e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 153.09it/s]
Epoch 501:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.48e+7, train_loss_epoch=2.48e+7, valid_loss=3.11e+7]
Epoch 505:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.34e+7, train_loss_epoch=3.34e+7, valid_loss=3.11e+7]
Epoch 509:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.6e+7, train_loss_epoch=3.6e+7, valid_loss=3.11e+7]
Epoch 513:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.46e+7, train_loss_epoch=2.46e+7, valid_loss=3.11e+7]
Epoch 516:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.8e+7, train_loss_epoch=1.8e+7, valid_loss=3.11e+7]
Epoch 520:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.56e+7, train_loss_epoch=2.56e+7, valid_loss=3.11e+7]
Epoch 524:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2e+7, train_loss_epoch=2e+7, valid_loss=3.11e+7]
Epoch 528:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.37e+7, train_loss_epoch=2.37e+7, valid_loss=3.11e+7]
Epoch 532:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.01e+7, train_loss_epoch=3.01e+7, valid_loss=3.11e+7]
Epoch 536:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.31e+7, train_loss_epoch=3.31e+7, valid_loss=3.11e+7]
Epoch 541:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.4e+7, train_loss_epoch=2.4e+7, valid_loss=3.11e+7]
Epoch 545:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.36e+7, train_loss_epoch=3.36e+7, valid_loss=3.11e+7]
Epoch 549:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.21e+7, train_loss_epoch=2.21e+7, valid_loss=3.11e+7]
Epoch 552: 100%|██████████| 1/1 [00:00<00:00, 34.48it/s, v_num=0, train_loss_step=3.35e+7, train_loss_epoch=2.01e+7, valid_loss=3.11e+7]
Epoch 555:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.19e+7, train_loss_epoch=2.19e+7, valid_loss=3.11e+7]
Epoch 558:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.86e+7, train_loss_epoch=2.86e+7, valid_loss=3.11e+7]
Epoch 558: 100%|██████████| 1/1 [00:00<00:00, 40.24it/s, v_num=0, train_loss_step=2.86e+7, train_loss_epoch=2.86e+7, valid_loss=3.11e+7]

(_train_tune pid=5763) `Trainer.fit` stopped: `max_steps=5000` reached.
(_train_tune pid=6383) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6383) Seed set to 18
(_train_tune pid=6383) GPU available: True (cuda), used: True
(_train_tune pid=6383) TPU available: False, using: 0 TPU cores
(_train_tune pid=6383) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=6383)
(_train_tune pid=6383)   | Name         | Type              | Params | Mode
(_train_tune pid=6383) -----------------------------------------------------------
(_train_tune pid=6383) 0 | loss         | MAE               | 0      | train
(_train_tune pid=6383) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=6383) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=6383) 3 | model        | PatchTST_backbone | 399 K  | train
(_train_tune pid=6383) -----------------------------------------------------------
(_train_tune pid=6383) 399 K     Trainable params
(_train_tune pid=6383) 3         Non-trainable params
(_train_tune pid=6383) 399 K     Total params
(_train_tune pid=6383) 1.599     Total estimated model params size (MB)
(_train_tune pid=6383) 90        Modules in train mode
(_train_tune pid=6383) 0         Modules in eval mode
(_train_tune pid=6383) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/3 [00:00<?, ?it/s]
Epoch 1:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=8.23e+6, train_loss_epoch=1.14e+7]
Epoch 2: 100%|██████████| 3/3 [00:00<00:00, 37.53it/s, v_num=0, train_loss_step=1.02e+7, train_loss_epoch=9.78e+6]
Epoch 4:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.76e+7, train_loss_epoch=1.17e+7]
Epoch 5:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.73e+7, train_loss_epoch=1.09e+7]
Epoch 7:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.18e+7, train_loss_epoch=1.26e+7]
Epoch 9:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.8e+7, train_loss_epoch=1.02e+7]
Epoch 11:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.35e+6, train_loss_epoch=9.99e+6]
Epoch 13:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.54e+6, train_loss_epoch=1.06e+7]
Epoch 15:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.42e+7, train_loss_epoch=1.32e+7]
Epoch 17:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.68e+7, train_loss_epoch=9.93e+6]
Epoch 19:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.15e+6, train_loss_epoch=1.02e+7]
Epoch 21:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.9e+6, train_loss_epoch=8.65e+6]
Epoch 23:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.54e+7, train_loss_epoch=1.09e+7]
Epoch 25:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.39e+7, train_loss_epoch=1.11e+7]
Epoch 27:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.43e+7, train_loss_epoch=1.07e+7]
Epoch 28:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.22e+7, train_loss_epoch=1.11e+7]
Epoch 30:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.25e+6, train_loss_epoch=9.75e+6]
Epoch 32:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.12e+6, train_loss_epoch=9.88e+6]
Epoch 33:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.06e+7, train_loss_epoch=1.03e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 159.42it/s]
Epoch 34:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2e+7, train_loss_epoch=1.3e+7, valid_loss=2.6e+7]
Epoch 36:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.71e+6, train_loss_epoch=7.24e+6, valid_loss=2.6e+7]
Epoch 37: 100%|██████████| 3/3 [00:00<00:00, 59.06it/s, v_num=0, train_loss_step=4.47e+6, train_loss_epoch=8.74e+6, valid_loss=2.6e+7]
Epoch 38:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.47e+6, train_loss_epoch=8.74e+6, valid_loss=2.6e+7]
Epoch 39: 100%|██████████| 3/3 [00:00<00:00, 61.98it/s, v_num=0, train_loss_step=2.05e+7, train_loss_epoch=1.16e+7, valid_loss=2.6e+7]
Epoch 40:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.05e+7, train_loss_epoch=1.16e+7, valid_loss=2.6e+7]
Epoch 41:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.49e+7, train_loss_epoch=1.23e+7, valid_loss=2.6e+7]
Epoch 43:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.23e+7, train_loss_epoch=9.87e+6, valid_loss=2.6e+7]
Epoch 45:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.06e+6, train_loss_epoch=9.12e+6, valid_loss=2.6e+7]
Epoch 46:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.09e+6, train_loss_epoch=9.07e+6, valid_loss=2.6e+7]
Epoch 48:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.61e+7, train_loss_epoch=1.28e+7, valid_loss=2.6e+7]
Epoch 50:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.48e+6, train_loss_epoch=9.53e+6, valid_loss=2.6e+7]
Epoch 52:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.35e+6, train_loss_epoch=8.67e+6, valid_loss=2.6e+7]
Epoch 54:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=8.89e+5, train_loss_epoch=8.69e+6, valid_loss=2.6e+7]
Epoch 56:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.51e+6, train_loss_epoch=7.81e+6, valid_loss=2.6e+7]
Epoch 58:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.76e+6, train_loss_epoch=8.23e+6, valid_loss=2.6e+7]
Epoch 60:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.23e+6, train_loss_epoch=9.07e+6, valid_loss=2.6e+7]
Epoch 61:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.25e+7, train_loss_epoch=5.79e+6, valid_loss=2.6e+7]
Epoch 63:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.45e+7, train_loss_epoch=1e+7, valid_loss=2.6e+7]
Epoch 65:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.98e+6, train_loss_epoch=1.02e+7, valid_loss=2.6e+7]
Epoch 66:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=8.97e+6, train_loss_epoch=8.9e+6, valid_loss=2.6e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 138.50it/s]
(_train_tune pid=6383)
Epoch 68:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.66e+7, train_loss_epoch=9.23e+6, valid_loss=2.73e+7]
Epoch 70:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.93e+7, train_loss_epoch=1.06e+7, valid_loss=2.73e+7]
Epoch 71:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.68e+7, train_loss_epoch=1.13e+7, valid_loss=2.73e+7]
Epoch 71: 100%|██████████| 3/3 [00:00<00:00, 57.31it/s, v_num=0, train_loss_step=1.77e+7, train_loss_epoch=1.13e+7, valid_loss=2.73e+7]
Epoch 73:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.6e+6, train_loss_epoch=6.55e+6, valid_loss=2.73e+7]
Epoch 75:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.31e+6, train_loss_epoch=8.54e+6, valid_loss=2.73e+7]
Epoch 77:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.02e+6, train_loss_epoch=7.19e+6, valid_loss=2.73e+7]
Epoch 79:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.27e+6, train_loss_epoch=9.16e+6, valid_loss=2.73e+7]
Epoch 81:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.42e+6, train_loss_epoch=7.72e+6, valid_loss=2.73e+7]
Epoch 82:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.13e+7, train_loss_epoch=9.81e+6, valid_loss=2.73e+7]
Epoch 84:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.87e+7, train_loss_epoch=8.17e+6, valid_loss=2.73e+7]
Epoch 86:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.7e+7, train_loss_epoch=1.03e+7, valid_loss=2.73e+7]
Epoch 88:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=8.36e+6, train_loss_epoch=7.4e+6, valid_loss=2.73e+7]
Epoch 90:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.33e+7, train_loss_epoch=9.54e+6, valid_loss=2.73e+7]
Epoch 92:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.5e+6, train_loss_epoch=9.05e+6, valid_loss=2.73e+7]
Epoch 94:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.81e+6, train_loss_epoch=7.91e+6, valid_loss=2.73e+7]
Epoch 96:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.06e+6, train_loss_epoch=8.32e+6, valid_loss=2.73e+7]
Epoch 98:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.14e+7, train_loss_epoch=1.32e+7, valid_loss=2.73e+7]
Epoch 99: 100%|██████████| 3/3 [00:00<00:00, 58.30it/s, v_num=0, train_loss_step=7.25e+6, train_loss_epoch=1.07e+7, valid_loss=2.73e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
(_train_tune pid=6383)
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 83.07it/s]
Epoch 100: 100%|██████████| 3/3 [00:00<00:00, 56.38it/s, v_num=0, train_loss_step=1.11e+7, train_loss_epoch=8.45e+6, valid_loss=2.74e+7]
Epoch 101:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.11e+7, train_loss_epoch=9.78e+6, valid_loss=2.74e+7]
Epoch 102:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.46e+6, train_loss_epoch=9.14e+6, valid_loss=2.74e+7]
Epoch 104:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.5e+6, train_loss_epoch=9.33e+6, valid_loss=2.74e+7]
Epoch 106:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.99e+6, train_loss_epoch=7.44e+6, valid_loss=2.74e+7]
Epoch 108:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.63e+7, train_loss_epoch=1.13e+7, valid_loss=2.74e+7]
Epoch 110:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.66e+6, train_loss_epoch=9.2e+6, valid_loss=2.74e+7]
Epoch 112:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.35e+7, train_loss_epoch=1.01e+7, valid_loss=2.74e+7]
Epoch 114:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.08e+7, train_loss_epoch=1.09e+7, valid_loss=2.74e+7]
Epoch 115: 100%|██████████| 3/3 [00:00<00:00, 59.12it/s, v_num=0, train_loss_step=3.1e+6, train_loss_epoch=7.96e+6, valid_loss=2.74e+7]
Epoch 116:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.1e+6, train_loss_epoch=7.96e+6, valid_loss=2.74e+7]
Epoch 117:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.28e+7, train_loss_epoch=8.62e+6, valid_loss=2.74e+7]
Epoch 119:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.09e+7, train_loss_epoch=9.6e+6, valid_loss=2.74e+7]
Epoch 121:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.82e+6, train_loss_epoch=7.57e+6, valid_loss=2.74e+7]
Epoch 123:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.4e+6, train_loss_epoch=8.44e+6, valid_loss=2.74e+7]
Epoch 125:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.5e+7, train_loss_epoch=1.01e+7, valid_loss=2.74e+7]
Epoch 127:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.85e+6, train_loss_epoch=9.14e+6, valid_loss=2.74e+7]
Epoch 128:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2e+7, train_loss_epoch=1.19e+7, valid_loss=2.74e+7]
Epoch 130:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.15e+7, train_loss_epoch=9.57e+6, valid_loss=2.74e+7]
Epoch 132:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.7e+6, train_loss_epoch=8.29e+6, valid_loss=2.74e+7]
Epoch 133:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.61e+6, train_loss_epoch=6.93e+6, valid_loss=2.74e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 171.96it/s]
Epoch 134:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.75e+6, train_loss_epoch=9.7e+6, valid_loss=2.34e+7]
Epoch 136:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.38e+6, train_loss_epoch=8.26e+6, valid_loss=2.34e+7]
Epoch 137:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.22e+6, train_loss_epoch=5.37e+6, valid_loss=2.34e+7]
Epoch 139:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.71e+6, train_loss_epoch=6.66e+6, valid_loss=2.34e+7]
Epoch 141:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.85e+6, train_loss_epoch=8.19e+6, valid_loss=2.34e+7]
Epoch 143:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.86e+7, train_loss_epoch=1.16e+7, valid_loss=2.34e+7]
Epoch 145:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.2e+6, train_loss_epoch=7.29e+6, valid_loss=2.34e+7]
Epoch 147:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.41e+6, train_loss_epoch=8.34e+6, valid_loss=2.34e+7]
Epoch 149:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.96e+6, train_loss_epoch=9.19e+6, valid_loss=2.34e+7]
Epoch 151:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.17e+6, train_loss_epoch=8.38e+6, valid_loss=2.34e+7]
Epoch 153:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.64e+7, train_loss_epoch=9.39e+6, valid_loss=2.34e+7]
Epoch 156:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.19e+7, train_loss_epoch=8.39e+6, valid_loss=2.34e+7]
Epoch 157:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.72e+6, train_loss_epoch=9.61e+6, valid_loss=2.34e+7]
Epoch 159:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.4e+6, train_loss_epoch=8.17e+6, valid_loss=2.34e+7]
Epoch 161:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.37e+6, train_loss_epoch=9.04e+6, valid_loss=2.34e+7]
Epoch 164:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.06e+7, train_loss_epoch=1.13e+7, valid_loss=2.34e+7]
Epoch 166:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=7.16e+6, train_loss_epoch=7.47e+6, valid_loss=2.34e+7]

(_train_tune pid=6383) `Trainer.fit` stopped: `max_steps=500` reached.

Epoch 166: 100%|██████████| 2/2 [00:00<00:00, 61.82it/s, v_num=0, train_loss_step=1.18e+7, train_loss_epoch=7.47e+6, valid_loss=2.34e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 188.57it/s]
Epoch 166: 100%|██████████| 2/2 [00:00<00:00, 30.90it/s, v_num=0, train_loss_step=1.18e+7, train_loss_epoch=7.2e+6, valid_loss=2.62e+7]

(_train_tune pid=6560) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6560) Seed set to 19
(_train_tune pid=6560) GPU available: True (cuda), used: True
(_train_tune pid=6560) TPU available: False, using: 0 TPU cores
(_train_tune pid=6560) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=6560)
(_train_tune pid=6560)   | Name         | Type              | Params | Mode
(_train_tune pid=6560) -----------------------------------------------------------
(_train_tune pid=6560) 0 | loss         | MAE               | 0      | train
(_train_tune pid=6560) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=6560) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=6560) 3 | model        | PatchTST_backbone | 29.1 K | train
(_train_tune pid=6560) -----------------------------------------------------------
(_train_tune pid=6560) 29.1 K    Trainable params
(_train_tune pid=6560) 3         Non-trainable params
(_train_tune pid=6560) 29.1 K    Total params
(_train_tune pid=6560) 0.117     Total estimated model params size (MB)
(_train_tune pid=6560) 89        Modules in train mode
(_train_tune pid=6560) 0         Modules in eval mode
(_train_tune pid=6560) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking: |          | 0/? [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 5:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.93e+3, train_loss_epoch=4.93e+3]
Epoch 10:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.49e+3, train_loss_epoch=2.49e+3]
Epoch 10: 100%|██████████| 1/1 [00:00<00:00, 49.37it/s, v_num=0, train_loss_step=2.49e+3, train_loss_epoch=2.49e+3]
Epoch 10:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.76e+3, train_loss_epoch=8.76e+3]
Epoch 11:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.76e+3, train_loss_epoch=8.76e+3]
Epoch 16:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5e+3, train_loss_epoch=5e+3]
Epoch 20:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.11e+3, train_loss_epoch=2.11e+3]
Epoch 21:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.14e+3, train_loss_epoch=8.14e+3]
Epoch 25: 100%|██████████| 1/1 [00:00<00:00, 46.46it/s, v_num=0, train_loss_step=5.14e+3, train_loss_epoch=5.14e+3]
Epoch 31:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.62e+3, train_loss_epoch=4.62e+3]
Epoch 35:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.68e+3, train_loss_epoch=5.68e+3]
Epoch 36:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.68e+3, train_loss_epoch=5.68e+3]
Epoch 41:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.2e+3, train_loss_epoch=8.2e+3]
Epoch 45:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8380.5, train_loss_epoch=8380.5]
Epoch 50:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.96e+3, train_loss_epoch=4.96e+3]
Epoch 55:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.47e+3, train_loss_epoch=4.47e+3]
Epoch 60:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.52e+3, train_loss_epoch=8.52e+3]
Epoch 65:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.35e+3, train_loss_epoch=8.35e+3]
Epoch 69:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.38e+3, train_loss_epoch=5.38e+3]
Epoch 75:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.9e+3, train_loss_epoch=7.9e+3]
Epoch 80:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.06e+3, train_loss_epoch=2.06e+3]
Epoch 85:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.41e+3, train_loss_epoch=8.41e+3]
Epoch 90:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.43e+3, train_loss_epoch=1.43e+3]
Epoch 95:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.78e+3, train_loss_epoch=7.78e+3]
Epoch 99: 100%|██████████| 1/1 [00:00<00:00, 53.83it/s, v_num=0, train_loss_step=8.09e+3, train_loss_epoch=4.8e+3]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
(_train_tune pid=6560)
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 137.70it/s]
(_train_tune pid=6560)
Epoch 104:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=6e+3, train_loss_epoch=6e+3, valid_loss=1.92e+7]
Epoch 109:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.09e+3, train_loss_epoch=8.09e+3, valid_loss=1.92e+7]
Epoch 109: 100%|██████████| 1/1 [00:00<00:00, 54.18it/s, v_num=0, train_loss_step=5.66e+3, train_loss_epoch=8.09e+3, valid_loss=1.92e+7]
Epoch 110:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.66e+3, train_loss_epoch=5.66e+3, valid_loss=1.92e+7]
Epoch 114:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.3e+3, train_loss_epoch=8.3e+3, valid_loss=1.92e+7]
Epoch 114: 100%|██████████| 1/1 [00:00<00:00, 31.10it/s, v_num=0, train_loss_step=8.37e+3, train_loss_epoch=8.37e+3, valid_loss=1.92e+7]
Epoch 115:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.37e+3, train_loss_epoch=8.37e+3, valid_loss=1.92e+7]
Epoch 120:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.54e+3, train_loss_epoch=8.54e+3, valid_loss=1.92e+7]
Epoch 125:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.63e+3, train_loss_epoch=8.63e+3, valid_loss=1.92e+7]
Epoch 129:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.03e+3, train_loss_epoch=5.03e+3, valid_loss=1.92e+7]
Epoch 134:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.47e+3, train_loss_epoch=2.47e+3, valid_loss=1.92e+7]
Epoch 139:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.89e+3, train_loss_epoch=7.89e+3, valid_loss=1.92e+7]
Epoch 145:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.96e+3, train_loss_epoch=5.96e+3, valid_loss=1.92e+7]
Epoch 150:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2e+3, train_loss_epoch=2e+3, valid_loss=1.92e+7]
Epoch 155:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.72e+3, train_loss_epoch=5.72e+3, valid_loss=1.92e+7]
Epoch 161:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.51e+3, train_loss_epoch=4.51e+3, valid_loss=1.92e+7]
Epoch 165:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.86e+3, train_loss_epoch=5.86e+3, valid_loss=1.92e+7]
Epoch 170:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.85e+3, train_loss_epoch=4.85e+3, valid_loss=1.92e+7]
Epoch 175:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.89e+3, train_loss_epoch=5.89e+3, valid_loss=1.92e+7]
Epoch 180:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.95e+3, train_loss_epoch=4.95e+3, valid_loss=1.92e+7]
Epoch 185:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=6.17e+3, train_loss_epoch=6.17e+3, valid_loss=1.92e+7]
Epoch 189:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.79e+3, train_loss_epoch=1.79e+3, valid_loss=1.92e+7]
Epoch 194:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.61e+3, train_loss_epoch=4.61e+3, valid_loss=1.92e+7]
Epoch 199:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.13e+3, train_loss_epoch=8.13e+3, valid_loss=1.92e+7]
Epoch 199: 100%|██████████| 1/1 [00:00<00:00, 49.95it/s, v_num=0, train_loss_step=1.27e+3, train_loss_epoch=8.13e+3, valid_loss=1.92e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 165.46it/s]
Epoch 203:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.6e+3, train_loss_epoch=8.6e+3, valid_loss=1.94e+7]
Epoch 209:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.04e+3, train_loss_epoch=8.04e+3, valid_loss=1.94e+7]
Epoch 213:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.11e+3, train_loss_epoch=8.11e+3, valid_loss=1.94e+7]
Epoch 218: 100%|██████████| 1/1 [00:00<00:00, 52.39it/s, v_num=0, train_loss_step=5.9e+3, train_loss_epoch=5.9e+3, valid_loss=1.94e+7]
Epoch 219:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.9e+3, train_loss_epoch=5.9e+3, valid_loss=1.94e+7]
Epoch 223:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.66e+3, train_loss_epoch=4.66e+3, valid_loss=1.94e+7]
Epoch 223: 100%|██████████| 1/1 [00:00<00:00, 42.55it/s, v_num=0, train_loss_step=9.1e+3, train_loss_epoch=9.1e+3, valid_loss=1.94e+7]
Epoch 228: 100%|██████████| 1/1 [00:00<00:00, 52.24it/s, v_num=0, train_loss_step=7.53e+3, train_loss_epoch=5.46e+3, valid_loss=1.94e+7]
Epoch 233:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.24e+3, train_loss_epoch=8.24e+3, valid_loss=1.94e+7]
Epoch 238:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.48e+3, train_loss_epoch=8.48e+3, valid_loss=1.94e+7]
Epoch 243:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.89e+3, train_loss_epoch=5.89e+3, valid_loss=1.94e+7]
Epoch 247:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.4e+3, train_loss_epoch=8.4e+3, valid_loss=1.94e+7]
Epoch 252:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.3e+3, train_loss_epoch=8.3e+3, valid_loss=1.94e+7]
Epoch 252: 100%|██████████| 1/1 [00:00<00:00, 44.08it/s, v_num=0, train_loss_step=8.3e+3, train_loss_epoch=8.3e+3, valid_loss=1.94e+7]
Epoch 253:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.3e+3, train_loss_epoch=8.3e+3, valid_loss=1.94e+7]
Epoch 257: 100%|██████████| 1/1 [00:00<00:00, 54.94it/s, v_num=0, train_loss_step=3.99e+3, train_loss_epoch=8.02e+3, valid_loss=1.94e+7]
Epoch 257: 100%|██████████| 1/1 [00:00<00:00, 52.88it/s, v_num=0, train_loss_step=3.99e+3, train_loss_epoch=3.99e+3, valid_loss=1.94e+7]
Epoch 257:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.99e+3, train_loss_epoch=3.99e+3, valid_loss=1.94e+7]
Epoch 258:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.99e+3, train_loss_epoch=3.99e+3, valid_loss=1.94e+7]
Epoch 262:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.67e+3, train_loss_epoch=8.67e+3, valid_loss=1.94e+7]
Epoch 268:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.23e+3, train_loss_epoch=8.23e+3, valid_loss=1.94e+7]
Epoch 273:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.15e+3, train_loss_epoch=8.15e+3, valid_loss=1.94e+7]
Epoch 278:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.97e+3, train_loss_epoch=5.97e+3, valid_loss=1.94e+7]
Epoch 283:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.78e+3, train_loss_epoch=7.78e+3, valid_loss=1.94e+7]
Epoch 289:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=6.19e+3, train_loss_epoch=6.19e+3, valid_loss=1.94e+7]
Epoch 294:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.28e+3, train_loss_epoch=8.28e+3, valid_loss=1.94e+7]
Epoch 299: 100%|██████████| 1/1 [00:00<00:00, 59.72it/s, v_num=0, train_loss_step=8.2e+3, train_loss_epoch=7.93e+3, valid_loss=1.94e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
(_train_tune pid=6560)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 161.47it/s]
Epoch 304:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.45e+3, train_loss_epoch=5.45e+3, valid_loss=1.98e+7]
Epoch 309:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.85e+3, train_loss_epoch=5.85e+3, valid_loss=1.98e+7]
Epoch 314:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.19e+3, train_loss_epoch=5.19e+3, valid_loss=1.98e+7]
Epoch 319:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.28e+3, train_loss_epoch=8.28e+3, valid_loss=1.98e+7]
Epoch 325:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.94e+3, train_loss_epoch=7.94e+3, valid_loss=1.98e+7]
Epoch 330:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.57e+3, train_loss_epoch=4.57e+3, valid_loss=1.98e+7]
Epoch 335:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=6.25e+3, train_loss_epoch=6.25e+3, valid_loss=1.98e+7]
Epoch 338:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.33e+3, train_loss_epoch=5.33e+3, valid_loss=1.98e+7]
Epoch 341:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.31e+3, train_loss_epoch=1.31e+3, valid_loss=1.98e+7]
Epoch 345:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.12e+3, train_loss_epoch=8.12e+3, valid_loss=1.98e+7]
Epoch 349:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.9e+3, train_loss_epoch=8.9e+3, valid_loss=1.98e+7]
Epoch 353:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.34e+3, train_loss_epoch=5.34e+3, valid_loss=1.98e+7]
Epoch 355:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.52e+3, train_loss_epoch=7.52e+3, valid_loss=1.98e+7]
Epoch 358:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.67e+3, train_loss_epoch=8.67e+3, valid_loss=1.98e+7]
Epoch 359:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.66e+3, train_loss_epoch=4.66e+3, valid_loss=1.98e+7]
Epoch 362:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.03e+3, train_loss_epoch=8.03e+3, valid_loss=1.98e+7]
Epoch 366:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.27e+3, train_loss_epoch=5.27e+3, valid_loss=1.98e+7]
Epoch 370:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.22e+3, train_loss_epoch=8.22e+3, valid_loss=1.98e+7]
Epoch 373:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.5e+3, train_loss_epoch=8.5e+3, valid_loss=1.98e+7]
Epoch 377:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.63e+3, train_loss_epoch=5.63e+3, valid_loss=1.98e+7]
Epoch 381:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.98e+3, train_loss_epoch=7.98e+3, valid_loss=1.98e+7]
Epoch 385:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.61e+3, train_loss_epoch=5.61e+3, valid_loss=1.98e+7]
Epoch 389:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.99e+3, train_loss_epoch=1.99e+3, valid_loss=1.98e+7]
Epoch 392:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.06e+3, train_loss_epoch=8.06e+3, valid_loss=1.98e+7]
Epoch 396:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.46e+3, train_loss_epoch=5.46e+3, valid_loss=1.98e+7]
Epoch 399:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.37e+3, train_loss_epoch=8.37e+3, valid_loss=1.98e+7]
Epoch 399: 100%|██████████| 1/1 [00:00<00:00, 32.99it/s, v_num=0, train_loss_step=4.73e+3, train_loss_epoch=8.37e+3, valid_loss=1.98e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 103.19it/s]
Epoch 402:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.01e+3, train_loss_epoch=8.01e+3, valid_loss=2.25e+7]
Epoch 406:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.63e+3, train_loss_epoch=8.63e+3, valid_loss=2.25e+7]
Epoch 409:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.13e+3, train_loss_epoch=8.13e+3, valid_loss=2.25e+7]
Epoch 413:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.72e+3, train_loss_epoch=8.72e+3, valid_loss=2.25e+7]
Epoch 416:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.19e+3, train_loss_epoch=8.19e+3, valid_loss=2.25e+7]
Epoch 419:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.18e+3, train_loss_epoch=2.18e+3, valid_loss=2.25e+7]
Epoch 422:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.16e+3, train_loss_epoch=8.16e+3, valid_loss=2.25e+7]
Epoch 426:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.22e+3, train_loss_epoch=5.22e+3, valid_loss=2.25e+7]
Epoch 429:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.78e+3, train_loss_epoch=8.78e+3, valid_loss=2.25e+7]
Epoch 433:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.72e+3, train_loss_epoch=8.72e+3, valid_loss=2.25e+7]
Epoch 436:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.41e+3, train_loss_epoch=8.41e+3, valid_loss=2.25e+7]
Epoch 439:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.87e+3, train_loss_epoch=4.87e+3, valid_loss=2.25e+7]
Epoch 441:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.76e+3, train_loss_epoch=4.76e+3, valid_loss=2.25e+7]
Epoch 442:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.89e+3, train_loss_epoch=5.89e+3, valid_loss=2.25e+7]
Epoch 445:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.69e+3, train_loss_epoch=4.69e+3, valid_loss=2.25e+7]
Epoch 449:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.83e+3, train_loss_epoch=5.83e+3, valid_loss=2.25e+7]
Epoch 452:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.36e+3, train_loss_epoch=4.36e+3, valid_loss=2.25e+7]
Epoch 455:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.68e+3, train_loss_epoch=5.68e+3, valid_loss=2.25e+7]
Epoch 458:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.67e+3, train_loss_epoch=8.67e+3, valid_loss=2.25e+7]
Epoch 461:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.26e+3, train_loss_epoch=4.26e+3, valid_loss=2.25e+7]
Epoch 464:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.27e+3, train_loss_epoch=2.27e+3, valid_loss=2.25e+7]
Epoch 468:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.75e+3, train_loss_epoch=4.75e+3, valid_loss=2.25e+7]
Epoch 473:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.1e+3, train_loss_epoch=5.1e+3, valid_loss=2.25e+7]
Epoch 479:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.28e+3, train_loss_epoch=8.28e+3, valid_loss=2.25e+7]
Epoch 483: 100%|██████████| 1/1 [00:00<00:00, 50.45it/s, v_num=0, train_loss_step=5.77e+3, train_loss_epoch=5.77e+3, valid_loss=2.25e+7]
Epoch 484:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.77e+3, train_loss_epoch=5.77e+3, valid_loss=2.25e+7]
Epoch 489:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.49e+3, train_loss_epoch=8.49e+3, valid_loss=2.25e+7]
Epoch 494:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.22e+3, train_loss_epoch=4.22e+3, valid_loss=2.25e+7]
Epoch 499: 100%|██████████| 1/1 [00:00<00:00, 52.82it/s, v_num=0, train_loss_step=8.34e+3, train_loss_epoch=8.3e+3, valid_loss=2.25e+7]
(_train_tune pid=6560)
Validation: |          | 0/? [00:00<?, ?it/s]

(_train_tune pid=6560) `Trainer.fit` stopped: `max_steps=500` reached.

(_train_tune pid=6560)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 146.26it/s]
Epoch 499: 100%|██████████| 1/1 [00:00<00:00, 21.90it/s, v_num=0, train_loss_step=8.34e+3, train_loss_epoch=8.34e+3, valid_loss=2.75e+7]

(_train_tune pid=6746) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=6746) Seed set to 6
(_train_tune pid=6746) GPU available: True (cuda), used: True
(_train_tune pid=6746) TPU available: False, using: 0 TPU cores
(_train_tune pid=6746) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=6746)
(_train_tune pid=6746)   | Name         | Type              | Params | Mode
(_train_tune pid=6746) -----------------------------------------------------------
(_train_tune pid=6746) 0 | loss         | MAE               | 0      | train
(_train_tune pid=6746) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=6746) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=6746) 3 | model        | PatchTST_backbone | 29.1 K | train
(_train_tune pid=6746) -----------------------------------------------------------
(_train_tune pid=6746) 29.1 K    Trainable params
(_train_tune pid=6746) 3         Non-trainable params
(_train_tune pid=6746) 29.1 K    Total params
(_train_tune pid=6746) 0.117     Total estimated model params size (MB)
(_train_tune pid=6746) 89        Modules in train mode
(_train_tune pid=6746) 0         Modules in eval mode
(_train_tune pid=6746) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking: |          | 0/? [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/3 [00:00<?, ?it/s]
Epoch 1:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.18e+7, train_loss_epoch=1.5e+7]
Epoch 3:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.2e+7, train_loss_epoch=1.53e+7]
Epoch 6:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.83e+7, train_loss_epoch=1.52e+7]
Epoch 8:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.11e+7, train_loss_epoch=1.42e+7]
Epoch 10:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.93e+6, train_loss_epoch=1.46e+7]
Epoch 12:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.42e+7, train_loss_epoch=1.48e+7]
Epoch 14:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=8.02e+5, train_loss_epoch=1.3e+7]
Epoch 16:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.09e+7, train_loss_epoch=1.42e+7]
Epoch 18:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.19e+7, train_loss_epoch=1.72e+7]
Epoch 20:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.8e+6, train_loss_epoch=1.47e+7]
Epoch 21:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.51e+7, train_loss_epoch=1.66e+7]
Epoch 21: 100%|██████████| 3/3 [00:00<00:00, 57.23it/s, v_num=0, train_loss_step=1.99e+7, train_loss_epoch=1.66e+7]
Epoch 21: 100%|██████████| 3/3 [00:00<00:00, 56.46it/s, v_num=0, train_loss_step=1.99e+7, train_loss_epoch=1.71e+7]
Epoch 22:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.99e+7, train_loss_epoch=1.71e+7]
Epoch 23:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.84e+7, train_loss_epoch=1.72e+7]
Epoch 23: 100%|██████████| 3/3 [00:00<00:00, 60.60it/s, v_num=0, train_loss_step=1.84e+7, train_loss_epoch=1.72e+7]
Epoch 23: 100%|██████████| 3/3 [00:00<00:00, 58.94it/s, v_num=0, train_loss_step=3.95e+6, train_loss_epoch=1.12e+7]
Epoch 24:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.95e+6, train_loss_epoch=1.12e+7]
Epoch 25:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.72e+7, train_loss_epoch=1.59e+7]
Epoch 28:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.79e+7, train_loss_epoch=1.4e+7]
Epoch 30:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.56e+6, train_loss_epoch=1.18e+7]
Epoch 32:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.28e+7, train_loss_epoch=1.31e+7]
Epoch 33:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.55e+6, train_loss_epoch=1.2e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 182.55it/s]
Epoch 33:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.86e+6, train_loss_epoch=1.2e+7, valid_loss=3.11e+7]
Epoch 35: 100%|██████████| 3/3 [00:00<00:00, 66.41it/s, v_num=0, train_loss_step=1.94e+7, train_loss_epoch=1.75e+7, valid_loss=3.11e+7]
Epoch 36:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.94e+7, train_loss_epoch=1.75e+7, valid_loss=3.11e+7]
Epoch 37: 100%|██████████| 3/3 [00:00<00:00, 53.05it/s, v_num=0, train_loss_step=1.07e+6, train_loss_epoch=1.74e+7, valid_loss=3.11e+7]
Epoch 37: 100%|██████████| 3/3 [00:00<00:00, 50.16it/s, v_num=0, train_loss_step=1.07e+6, train_loss_epoch=1.66e+7, valid_loss=3.11e+7]
Epoch 39:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.5e+6, train_loss_epoch=1.71e+7, valid_loss=3.11e+7]
Epoch 40:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.53e+6, train_loss_epoch=1.18e+7, valid_loss=3.11e+7]
Epoch 41:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.55e+6, train_loss_epoch=1.37e+7, valid_loss=3.11e+7]
Epoch 43:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.96e+7, train_loss_epoch=1.45e+7, valid_loss=3.11e+7]
Epoch 44:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.92e+7, train_loss_epoch=1.29e+7, valid_loss=3.11e+7]
Epoch 45:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.32e+7, train_loss_epoch=1.45e+7, valid_loss=3.11e+7]
Epoch 47:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.65e+6, train_loss_epoch=1.7e+7, valid_loss=3.11e+7]
Epoch 48:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.83e+6, train_loss_epoch=1.42e+7, valid_loss=3.11e+7]
Epoch 50:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.95e+6, train_loss_epoch=1.54e+7, valid_loss=3.11e+7]
Epoch 51:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.11e+7, train_loss_epoch=1.62e+7, valid_loss=3.11e+7]
Epoch 52:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.83e+6, train_loss_epoch=1.59e+7, valid_loss=3.11e+7]
Epoch 54:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.73e+7, train_loss_epoch=1.7e+7, valid_loss=3.11e+7]
Epoch 56:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.21e+6, train_loss_epoch=1.29e+7, valid_loss=3.11e+7]
Epoch 58:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.77e+6, train_loss_epoch=1.41e+7, valid_loss=3.11e+7]
Epoch 59:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.09e+7, train_loss_epoch=1.64e+7, valid_loss=3.11e+7]
Epoch 61:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.25e+7, train_loss_epoch=1.27e+7, valid_loss=3.11e+7]
Epoch 63:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.92e+6, train_loss_epoch=1.81e+7, valid_loss=3.11e+7]
Epoch 64:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.59e+7, train_loss_epoch=1.62e+7, valid_loss=3.11e+7]
Epoch 66:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.45e+5, train_loss_epoch=1.89e+7, valid_loss=3.11e+7]
(_train_tune pid=6746)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 108.88it/s]
Epoch 66:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.18e+6, train_loss_epoch=1.89e+7, valid_loss=3.11e+7]
Epoch 67:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=8.78e+6, train_loss_epoch=1.41e+7, valid_loss=3.11e+7]
Epoch 69:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.28e+6, train_loss_epoch=1.68e+7, valid_loss=3.11e+7]
Epoch 70:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.64e+6, train_loss_epoch=1.34e+7, valid_loss=3.11e+7]
Epoch 72:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.41e+7, train_loss_epoch=1.81e+7, valid_loss=3.11e+7]
Epoch 73:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.01e+7, train_loss_epoch=1.62e+7, valid_loss=3.11e+7]
Epoch 73: 100%|██████████| 3/3 [00:00<00:00, 42.42it/s, v_num=0, train_loss_step=1.6e+7, train_loss_epoch=1.62e+7, valid_loss=3.11e+7]
Epoch 74:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.6e+7, train_loss_epoch=1.46e+7, valid_loss=3.11e+7]
Epoch 75:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.2e+7, train_loss_epoch=1.54e+7, valid_loss=3.11e+7]
Epoch 76:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.02e+7, train_loss_epoch=1.39e+7, valid_loss=3.11e+7]
Epoch 78:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.4e+7, train_loss_epoch=1.41e+7, valid_loss=3.11e+7]
Epoch 79:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.95e+7, train_loss_epoch=1.52e+7, valid_loss=3.11e+7]
Epoch 80:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.45e+6, train_loss_epoch=1.53e+7, valid_loss=3.11e+7]
Epoch 81:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.81e+7, train_loss_epoch=1.47e+7, valid_loss=3.11e+7]
Epoch 82:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.54e+6, train_loss_epoch=1.38e+7, valid_loss=3.11e+7]
Epoch 84:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.28e+6, train_loss_epoch=1.35e+7, valid_loss=3.11e+7]
Epoch 85:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.1e+6, train_loss_epoch=1.25e+7, valid_loss=3.11e+7]
Epoch 86:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.92e+6, train_loss_epoch=1.52e+7, valid_loss=3.11e+7]
Epoch 87:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.26e+7, train_loss_epoch=1.56e+7, valid_loss=3.11e+7]
Epoch 89:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.18e+7, train_loss_epoch=1.55e+7, valid_loss=3.11e+7]
Epoch 90:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.23e+7, train_loss_epoch=1.49e+7, valid_loss=3.11e+7]
Epoch 91:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.92e+6, train_loss_epoch=1.48e+7, valid_loss=3.11e+7]
Epoch 93:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.28e+6, train_loss_epoch=1.49e+7, valid_loss=3.11e+7]
Epoch 95:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.22e+7, train_loss_epoch=1.52e+7, valid_loss=3.11e+7]
Epoch 97:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.63e+6, train_loss_epoch=1.6e+7, valid_loss=3.11e+7]
Epoch 99:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.63e+7, train_loss_epoch=1.5e+7, valid_loss=3.11e+7]
Epoch 99: 100%|██████████| 3/3 [00:00<00:00, 57.47it/s, v_num=0, train_loss_step=7.78e+6, train_loss_epoch=1.5e+7, valid_loss=3.11e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 160.74it/s]
Epoch 100:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.78e+6, train_loss_epoch=1.38e+7, valid_loss=3.11e+7]
Epoch 102:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.86e+7, train_loss_epoch=1.55e+7, valid_loss=3.11e+7]
Epoch 103:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.72e+7, train_loss_epoch=1.79e+7, valid_loss=3.11e+7]
Epoch 105:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.74e+7, train_loss_epoch=1.34e+7, valid_loss=3.11e+7]
Epoch 107:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.62e+6, train_loss_epoch=1.52e+7, valid_loss=3.11e+7]
Epoch 108:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.89e+6, train_loss_epoch=1.32e+7, valid_loss=3.11e+7]
Epoch 110:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.43e+7, train_loss_epoch=1.6e+7, valid_loss=3.11e+7]
Epoch 111: 100%|██████████| 3/3 [00:00<00:00, 51.23it/s, v_num=0, train_loss_step=2.1e+7, train_loss_epoch=1.53e+7, valid_loss=3.11e+7]
Epoch 112:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.1e+7, train_loss_epoch=1.53e+7, valid_loss=3.11e+7]
Epoch 113:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4e+7, train_loss_epoch=1.93e+7, valid_loss=3.11e+7]
Epoch 115:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.7e+6, train_loss_epoch=1.42e+7, valid_loss=3.11e+7]
Epoch 118:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.21e+7, train_loss_epoch=1.58e+7, valid_loss=3.11e+7]
Epoch 120:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.09e+7, train_loss_epoch=1.4e+7, valid_loss=3.11e+7]
Epoch 122:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=8e+5, train_loss_epoch=1.59e+7, valid_loss=3.11e+7]
Epoch 123: 100%|██████████| 3/3 [00:00<00:00, 57.15it/s, v_num=0, train_loss_step=2.55e+7, train_loss_epoch=1.62e+7, valid_loss=3.11e+7]
Epoch 124:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.55e+7, train_loss_epoch=1.62e+7, valid_loss=3.11e+7]
Epoch 126:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.55e+7, train_loss_epoch=1.8e+7, valid_loss=3.11e+7]
Epoch 128:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.78e+7, train_loss_epoch=1.53e+7, valid_loss=3.11e+7]
Epoch 130:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.95e+7, train_loss_epoch=1.46e+7, valid_loss=3.11e+7]
Epoch 132:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.29e+7, train_loss_epoch=1.63e+7, valid_loss=3.11e+7]
Epoch 133:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.77e+7, train_loss_epoch=1.82e+7, valid_loss=3.11e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 166.60it/s]
(_train_tune pid=6746)
Epoch 135:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.56e+7, train_loss_epoch=1.58e+7, valid_loss=3.11e+7]
Epoch 136:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.21e+6, train_loss_epoch=1.5e+7, valid_loss=3.11e+7]
Epoch 138:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.06e+6, train_loss_epoch=1.49e+7, valid_loss=3.11e+7]
Epoch 140:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.62e+6, train_loss_epoch=1.41e+7, valid_loss=3.11e+7]
Epoch 142:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.18e+7, train_loss_epoch=1.29e+7, valid_loss=3.11e+7]
Epoch 144:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.32e+6, train_loss_epoch=1.6e+7, valid_loss=3.11e+7]
Epoch 146:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.01e+6, train_loss_epoch=1.31e+7, valid_loss=3.11e+7]
Epoch 148:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.87e+6, train_loss_epoch=1.45e+7, valid_loss=3.11e+7]
Epoch 150:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.21e+7, train_loss_epoch=1.41e+7, valid_loss=3.11e+7]
Epoch 152:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.5e+7, train_loss_epoch=1.61e+7, valid_loss=3.11e+7]
Epoch 154:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.84e+7, train_loss_epoch=1.35e+7, valid_loss=3.11e+7]
Epoch 156:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.13e+7, train_loss_epoch=1.51e+7, valid_loss=3.11e+7]
Epoch 158:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.68e+6, train_loss_epoch=1.43e+7, valid_loss=3.11e+7]
Epoch 160:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.53e+7, train_loss_epoch=1.45e+7, valid_loss=3.11e+7]
Epoch 162:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.76e+7, train_loss_epoch=1.44e+7, valid_loss=3.11e+7]
Epoch 164:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.11e+7, train_loss_epoch=1.33e+7, valid_loss=3.11e+7]
Epoch 166:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.16e+7, train_loss_epoch=1.56e+7, valid_loss=3.11e+7]
(_train_tune pid=6746)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 151.85it/s]
Epoch 167:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.68e+6, train_loss_epoch=1.45e+7, valid_loss=3.11e+7]
Epoch 169:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.69e+7, train_loss_epoch=1.89e+7, valid_loss=3.11e+7]
Epoch 171:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=5.53e+6, train_loss_epoch=1.55e+7, valid_loss=3.11e+7]
Epoch 172:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.77e+7, train_loss_epoch=1.6e+7, valid_loss=3.11e+7]
Epoch 174:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.44e+7, train_loss_epoch=1.63e+7, valid_loss=3.11e+7]
Epoch 176:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.02e+7, train_loss_epoch=1.52e+7, valid_loss=3.11e+7]
Epoch 178:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.36e+7, train_loss_epoch=1.68e+7, valid_loss=3.11e+7]
Epoch 180:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.06e+7, train_loss_epoch=1.55e+7, valid_loss=3.11e+7]
Epoch 182:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.17e+7, train_loss_epoch=1.52e+7, valid_loss=3.11e+7]
Epoch 184:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.87e+7, train_loss_epoch=1.5e+7, valid_loss=3.11e+7]
Epoch 186:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.63e+6, train_loss_epoch=1.39e+7, valid_loss=3.11e+7]
Epoch 188:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.76e+6, train_loss_epoch=1.55e+7, valid_loss=3.11e+7]
Epoch 190:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.12e+6, train_loss_epoch=1.59e+7, valid_loss=3.11e+7]
Epoch 192:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=9.53e+6, train_loss_epoch=1.67e+7, valid_loss=3.11e+7]
Epoch 194:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.5e+7, train_loss_epoch=1.78e+7, valid_loss=3.11e+7]
Epoch 196:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.3e+7, train_loss_epoch=1.34e+7, valid_loss=3.11e+7]
Epoch 197:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.79e+7, train_loss_epoch=1.25e+7, valid_loss=3.11e+7]
Epoch 199: 100%|██████████| 3/3 [00:00<00:00, 64.54it/s, v_num=0, train_loss_step=8.9e+6, train_loss_epoch=1.7e+7, valid_loss=3.11e+7]
(_train_tune pid=6746)
Validation: |          | 0/? [00:00<?, ?it/s]
(_train_tune pid=6746)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
(_train_tune pid=6746)
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 143.28it/s]
Epoch 201:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.39e+6, train_loss_epoch=1.36e+7, valid_loss=3.11e+7]
Epoch 203:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.76e+7, train_loss_epoch=1.37e+7, valid_loss=3.11e+7]
Epoch 205:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.81e+5, train_loss_epoch=1.39e+7, valid_loss=3.11e+7]
Epoch 207:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.52e+6, train_loss_epoch=1.38e+7, valid_loss=3.11e+7]
Epoch 208:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=7.51e+6, train_loss_epoch=1.1e+7, valid_loss=3.11e+7]
Epoch 210:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.1e+7, train_loss_epoch=1.59e+7, valid_loss=3.11e+7]
Epoch 212:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.42e+7, train_loss_epoch=1.48e+7, valid_loss=3.11e+7]
Epoch 214:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.7e+6, train_loss_epoch=1.45e+7, valid_loss=3.11e+7]
Epoch 216:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.44e+7, train_loss_epoch=1.75e+7, valid_loss=3.11e+7]
Epoch 218:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=8.53e+6, train_loss_epoch=1.46e+7, valid_loss=3.11e+7]
Epoch 220:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=2.28e+7, train_loss_epoch=1.41e+7, valid_loss=3.11e+7]
Epoch 222:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=4.13e+6, train_loss_epoch=1.72e+7, valid_loss=3.11e+7]
Epoch 224:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=3.36e+7, train_loss_epoch=1.67e+7, valid_loss=3.11e+7]
Epoch 226:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=1.97e+7, train_loss_epoch=1.54e+7, valid_loss=3.11e+7]
Epoch 228:   0%|          | 0/3 [00:00<?, ?it/s, v_num=0, train_loss_step=6.12e+6, train_loss_epoch=1.57e+7, valid_loss=3.11e+7]

(_train_tune pid=6746) `Trainer.fit` stopped: `max_steps=5000` reached.

Epoch 1666: 100%|██████████| 2/2 [00:00<00:00, 61.17it/s, v_num=0, train_loss_step=1.53e+7, train_loss_epoch=1.73e+7, valid_loss=3.11e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/3 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 3/3 [00:00<00:00, 177.93it/s]
Epoch 1666: 100%|██████████| 2/2 [00:00<00:00, 30.55it/s, v_num=0, train_loss_step=1.53e+7, train_loss_epoch=8.69e+6, valid_loss=3.11e+7]

(_train_tune pid=7308) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7308) Seed set to 11
(_train_tune pid=7308) GPU available: True (cuda), used: True
(_train_tune pid=7308) TPU available: False, using: 0 TPU cores
(_train_tune pid=7308) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=7308)
(_train_tune pid=7308)   | Name         | Type              | Params | Mode
(_train_tune pid=7308) -----------------------------------------------------------
(_train_tune pid=7308) 0 | loss         | MAE               | 0      | train
(_train_tune pid=7308) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=7308) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=7308) 3 | model        | PatchTST_backbone | 400 K  | train
(_train_tune pid=7308) -----------------------------------------------------------
(_train_tune pid=7308) 400 K     Trainable params
(_train_tune pid=7308) 3         Non-trainable params
(_train_tune pid=7308) 400 K     Total params
(_train_tune pid=7308) 1.603     Total estimated model params size (MB)
(_train_tune pid=7308) 90        Modules in train mode
(_train_tune pid=7308) 0         Modules in eval mode
(_train_tune pid=7308) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]

Epoch 0:   0%|          | 0/6 [00:00<?, ?it/s]
Epoch 1:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=5.170, train_loss_epoch=500.0]
Epoch 2:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.5e+3, train_loss_epoch=437.0]
Epoch 3:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.170, train_loss_epoch=398.0]
Epoch 4:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.750, train_loss_epoch=490.0]
Epoch 5:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.9e+3, train_loss_epoch=644.0]
Epoch 6:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=249.0, train_loss_epoch=436.0]
Epoch 7:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.830, train_loss_epoch=338.0]
Epoch 8:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.83e+3, train_loss_epoch=466.0]
Epoch 9:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.220, train_loss_epoch=524.0]
Epoch 10:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=324.0, train_loss_epoch=344.0]
Epoch 11:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.59e+3, train_loss_epoch=652.0]
Epoch 12:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=852.0, train_loss_epoch=304.0]
Epoch 13:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=908.0, train_loss_epoch=366.0]
Epoch 14:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.770, train_loss_epoch=357.0]
Epoch 15:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.19e+3, train_loss_epoch=451.0]
Epoch 16:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.22e+3, train_loss_epoch=478.0]
(_train_tune pid=7308)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 144.01it/s]
(_train_tune pid=7308)
Epoch 17:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.04e+3, train_loss_epoch=510.0, valid_loss=2.14e+7]
Epoch 18:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.99e+3, train_loss_epoch=603.0, valid_loss=2.14e+7]
Epoch 19:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=821.0, train_loss_epoch=274.0, valid_loss=2.14e+7]
Epoch 20:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.620, train_loss_epoch=498.0, valid_loss=2.14e+7]
Epoch 20: 100%|██████████| 6/6 [00:00<00:00, 42.72it/s, v_num=0, train_loss_step=298.0, train_loss_epoch=249.0, valid_loss=2.14e+7]
Epoch 21:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=298.0, train_loss_epoch=249.0, valid_loss=2.14e+7]
Epoch 22:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.010, train_loss_epoch=559.0, valid_loss=2.14e+7]
Epoch 23:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=139.0, train_loss_epoch=559.0, valid_loss=2.14e+7]
Epoch 24:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=5.780, train_loss_epoch=346.0, valid_loss=2.14e+7]
Epoch 25:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.260, train_loss_epoch=591.0, valid_loss=2.14e+7]
Epoch 26:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.73e+3, train_loss_epoch=664.0, valid_loss=2.14e+7]
Epoch 27:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=724.0, train_loss_epoch=363.0, valid_loss=2.14e+7]
Epoch 28:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=580.0, train_loss_epoch=469.0, valid_loss=2.14e+7]
Epoch 29:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.956, train_loss_epoch=640.0, valid_loss=2.14e+7]
Epoch 30:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.380, train_loss_epoch=406.0, valid_loss=2.14e+7]
Epoch 31:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.910, train_loss_epoch=355.0, valid_loss=2.14e+7]
Epoch 32:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=17.20, train_loss_epoch=307.0, valid_loss=2.14e+7]
Epoch 33:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.350, train_loss_epoch=368.0, valid_loss=2.14e+7]
(_train_tune pid=7308)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 110.54it/s]
Epoch 33:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.1e+3, train_loss_epoch=368.0, valid_loss=2.25e+7]
Epoch 34:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=674.0, train_loss_epoch=508.0, valid_loss=2.25e+7]
Epoch 35:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.490, train_loss_epoch=453.0, valid_loss=2.25e+7]
Epoch 36:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.260, train_loss_epoch=395.0, valid_loss=2.25e+7]
Epoch 37:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.360, train_loss_epoch=387.0, valid_loss=2.25e+7]
Epoch 38:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=378.0, train_loss_epoch=523.0, valid_loss=2.25e+7]
Epoch 39:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=353.0, train_loss_epoch=496.0, valid_loss=2.25e+7]
Epoch 40:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=9.950, train_loss_epoch=545.0, valid_loss=2.25e+7]
Epoch 41:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.61e+3, train_loss_epoch=513.0, valid_loss=2.25e+7]
Epoch 42:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.39e+3, train_loss_epoch=560.0, valid_loss=2.25e+7]
Epoch 43:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.950, train_loss_epoch=520.0, valid_loss=2.25e+7]
Epoch 44:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=14.60, train_loss_epoch=412.0, valid_loss=2.25e+7]
Epoch 45:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.668, train_loss_epoch=463.0, valid_loss=2.25e+7]
Epoch 46:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=149.0, train_loss_epoch=557.0, valid_loss=2.25e+7]
Epoch 47:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.27e+3, train_loss_epoch=629.0, valid_loss=2.25e+7]
Epoch 48:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.32e+3, train_loss_epoch=488.0, valid_loss=2.25e+7]
Epoch 49:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=13.00, train_loss_epoch=455.0, valid_loss=2.25e+7]
Epoch 49: 100%|██████████| 6/6 [00:00<00:00, 56.61it/s, v_num=0, train_loss_step=1.290, train_loss_epoch=455.0, valid_loss=2.25e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 147.27it/s]
Epoch 50:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.290, train_loss_epoch=422.0, valid_loss=2.38e+7]
Epoch 51:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=202.0, train_loss_epoch=264.0, valid_loss=2.38e+7]
Epoch 52:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=17.30, train_loss_epoch=411.0, valid_loss=2.38e+7]
Epoch 53:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=370.0, train_loss_epoch=385.0, valid_loss=2.38e+7]
Epoch 54:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.500, train_loss_epoch=179.0, valid_loss=2.38e+7]
Epoch 55:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=973.0, train_loss_epoch=426.0, valid_loss=2.38e+7]
Epoch 56:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=637.0, train_loss_epoch=464.0, valid_loss=2.38e+7]
Epoch 57:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=272.0, train_loss_epoch=311.0, valid_loss=2.38e+7]
Epoch 58:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.500, train_loss_epoch=479.0, valid_loss=2.38e+7]
Epoch 59:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.2e+3, train_loss_epoch=413.0, valid_loss=2.38e+7]
Epoch 60:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=12.40, train_loss_epoch=367.0, valid_loss=2.38e+7]
Epoch 61:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.270, train_loss_epoch=363.0, valid_loss=2.38e+7]
Epoch 62:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=849.0, train_loss_epoch=390.0, valid_loss=2.38e+7]
Epoch 63:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.3e+3, train_loss_epoch=466.0, valid_loss=2.38e+7]
Epoch 64:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.130, train_loss_epoch=365.0, valid_loss=2.38e+7]
Epoch 65:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.740, train_loss_epoch=429.0, valid_loss=2.38e+7]
Epoch 66:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=9.280, train_loss_epoch=391.0, valid_loss=2.38e+7]
(_train_tune pid=7308)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 149.81it/s]
(_train_tune pid=7308)
Epoch 67:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.750, train_loss_epoch=485.0, valid_loss=2.1e+7]
Epoch 68:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.360, train_loss_epoch=379.0, valid_loss=2.1e+7]
Epoch 69:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=457.0, train_loss_epoch=449.0, valid_loss=2.1e+7]
Epoch 70:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.290, train_loss_epoch=477.0, valid_loss=2.1e+7]
Epoch 71:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=10.20, train_loss_epoch=452.0, valid_loss=2.1e+7]
Epoch 72:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.34e+3, train_loss_epoch=487.0, valid_loss=2.1e+7]
Epoch 73:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.250, train_loss_epoch=671.0, valid_loss=2.1e+7]
Epoch 74:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.25e+3, train_loss_epoch=461.0, valid_loss=2.1e+7]
Epoch 75:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=234.0, train_loss_epoch=477.0, valid_loss=2.1e+7]
Epoch 76:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.808, train_loss_epoch=341.0, valid_loss=2.1e+7]
Epoch 77:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=626.0, train_loss_epoch=445.0, valid_loss=2.1e+7]
Epoch 78:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=7.490, train_loss_epoch=429.0, valid_loss=2.1e+7]
Epoch 79:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=528.0, train_loss_epoch=401.0, valid_loss=2.1e+7]
Epoch 80:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.53e+3, train_loss_epoch=643.0, valid_loss=2.1e+7]
Epoch 81:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=473.0, train_loss_epoch=316.0, valid_loss=2.1e+7]
Epoch 82:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=6.990, train_loss_epoch=247.0, valid_loss=2.1e+7]
Epoch 83:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.923, train_loss_epoch=456.0, valid_loss=2.1e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
(_train_tune pid=7308)
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 98.55it/s]
Epoch 83:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.23e+3, train_loss_epoch=456.0, valid_loss=1.94e+7]
Epoch 84:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=15.50, train_loss_epoch=560.0, valid_loss=1.94e+7]
Epoch 85:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.080, train_loss_epoch=411.0, valid_loss=1.94e+7]
Epoch 86:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=334.0, train_loss_epoch=474.0, valid_loss=1.94e+7]
Epoch 87:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=972.0, train_loss_epoch=495.0, valid_loss=1.94e+7]
Epoch 88:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.220, train_loss_epoch=478.0, valid_loss=1.94e+7]
Epoch 89:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=246.0, train_loss_epoch=369.0, valid_loss=1.94e+7]
Epoch 90:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=826.0, train_loss_epoch=384.0, valid_loss=1.94e+7]
Epoch 91:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.460, train_loss_epoch=538.0, valid_loss=1.94e+7]
Epoch 92:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.920, train_loss_epoch=802.0, valid_loss=1.94e+7]
Epoch 93:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=14.20, train_loss_epoch=637.0, valid_loss=1.94e+7]
Epoch 94:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.35e+3, train_loss_epoch=643.0, valid_loss=1.94e+7]
Epoch 95:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=285.0, train_loss_epoch=468.0, valid_loss=1.94e+7]
Epoch 96:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=449.0, train_loss_epoch=379.0, valid_loss=1.94e+7]
Epoch 97:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=880.0, train_loss_epoch=394.0, valid_loss=1.94e+7]
Epoch 98:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.966, train_loss_epoch=500.0, valid_loss=1.94e+7]
Epoch 99:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.280, train_loss_epoch=442.0, valid_loss=1.94e+7]
Epoch 99: 100%|██████████| 6/6 [00:00<00:00, 53.41it/s, v_num=0, train_loss_step=14.40, train_loss_epoch=442.0, valid_loss=1.94e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 140.39it/s]
Epoch 100:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=14.40, train_loss_epoch=494.0, valid_loss=1.89e+7]
Epoch 101:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=764.0, train_loss_epoch=566.0, valid_loss=1.89e+7]
Epoch 103:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.220, train_loss_epoch=364.0, valid_loss=1.89e+7]
Epoch 104:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=5.260, train_loss_epoch=417.0, valid_loss=1.89e+7]
Epoch 105:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.420, train_loss_epoch=358.0, valid_loss=1.89e+7]
Epoch 106:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.470, train_loss_epoch=340.0, valid_loss=1.89e+7]
Epoch 107:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.500, train_loss_epoch=404.0, valid_loss=1.89e+7]
Epoch 108:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.762, train_loss_epoch=358.0, valid_loss=1.89e+7]
Epoch 109:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=502.0, train_loss_epoch=403.0, valid_loss=1.89e+7]
Epoch 110:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.926, train_loss_epoch=491.0, valid_loss=1.89e+7]
Epoch 111:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.020, train_loss_epoch=463.0, valid_loss=1.89e+7]
Epoch 112:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=609.0, train_loss_epoch=429.0, valid_loss=1.89e+7]
Epoch 113:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.120, train_loss_epoch=440.0, valid_loss=1.89e+7]
Epoch 114:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.747, train_loss_epoch=352.0, valid_loss=1.89e+7]
Epoch 115:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.920, train_loss_epoch=639.0, valid_loss=1.89e+7]
Epoch 116:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.27e+3, train_loss_epoch=466.0, valid_loss=1.89e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
(_train_tune pid=7308)
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 127.48it/s]
Epoch 117:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=189.0, train_loss_epoch=411.0, valid_loss=2.28e+7]
Epoch 118:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.32e+3, train_loss_epoch=525.0, valid_loss=2.28e+7]
Epoch 119:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.11e+3, train_loss_epoch=748.0, valid_loss=2.28e+7]
Epoch 120:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.920, train_loss_epoch=422.0, valid_loss=2.28e+7]
Epoch 121:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.3e+3, train_loss_epoch=526.0, valid_loss=2.28e+7]
Epoch 122:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.570, train_loss_epoch=445.0, valid_loss=2.28e+7]
Epoch 123:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.02e+3, train_loss_epoch=315.0, valid_loss=2.28e+7]
Epoch 124:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.810, train_loss_epoch=427.0, valid_loss=2.28e+7]
Epoch 125:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.300, train_loss_epoch=442.0, valid_loss=2.28e+7]
Epoch 125: 100%|██████████| 6/6 [00:00<00:00, 58.46it/s, v_num=0, train_loss_step=10.60, train_loss_epoch=440.0, valid_loss=2.28e+7]
Epoch 126:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=10.60, train_loss_epoch=440.0, valid_loss=2.28e+7]
Epoch 126: 100%|██████████| 6/6 [00:00<00:00, 55.41it/s, v_num=0, train_loss_step=1.7e+3, train_loss_epoch=561.0, valid_loss=2.28e+7]
Epoch 127:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.7e+3, train_loss_epoch=561.0, valid_loss=2.28e+7]
Epoch 128:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=797.0, train_loss_epoch=571.0, valid_loss=2.28e+7]
Epoch 129:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.64e+3, train_loss_epoch=531.0, valid_loss=2.28e+7]
Epoch 130:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.13e+3, train_loss_epoch=602.0, valid_loss=2.28e+7]
Epoch 131:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.55e+3, train_loss_epoch=423.0, valid_loss=2.28e+7]
Epoch 132:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.360, train_loss_epoch=560.0, valid_loss=2.28e+7]
Epoch 133:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=20.50, train_loss_epoch=460.0, valid_loss=2.28e+7]
(_train_tune pid=7308)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 110.14it/s]
Epoch 133:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.490, train_loss_epoch=460.0, valid_loss=2.22e+7]
Epoch 134:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.420, train_loss_epoch=544.0, valid_loss=2.22e+7]
Epoch 135:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=297.0, train_loss_epoch=358.0, valid_loss=2.22e+7]
Epoch 136:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.03e+3, train_loss_epoch=427.0, valid_loss=2.22e+7]
Epoch 137:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=6.190, train_loss_epoch=312.0, valid_loss=2.22e+7]
Epoch 138:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=862.0, train_loss_epoch=447.0, valid_loss=2.22e+7]

(_train_tune pid=7308) `Trainer.fit` stopped: `max_steps=1000` reached.
(_train_tune pid=7530) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7530) Seed set to 7
(_train_tune pid=7530) GPU available: True (cuda), used: True
(_train_tune pid=7530) TPU available: False, using: 0 TPU cores
(_train_tune pid=7530) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=7530)
(_train_tune pid=7530)   | Name         | Type              | Params | Mode
(_train_tune pid=7530) -----------------------------------------------------------
(_train_tune pid=7530) 0 | loss         | MAE               | 0      | train
(_train_tune pid=7530) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=7530) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=7530) 3 | model        | PatchTST_backbone | 400 K  | train
(_train_tune pid=7530) -----------------------------------------------------------
(_train_tune pid=7530) 400 K     Trainable params
(_train_tune pid=7530) 3         Non-trainable params
(_train_tune pid=7530) 400 K     Total params
(_train_tune pid=7530) 1.601     Total estimated model params size (MB)
(_train_tune pid=7530) 89        Modules in train mode
(_train_tune pid=7530) 0         Modules in eval mode
(_train_tune pid=7530) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking: |          | 0/? [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 2:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=126.0, train_loss_epoch=126.0]
Epoch 7:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=781.0, train_loss_epoch=781.0]
Epoch 12:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=533.0, train_loss_epoch=533.0]
Epoch 17:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=712.0, train_loss_epoch=712.0]
Epoch 21:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=788.0, train_loss_epoch=788.0]
Epoch 26:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=362.0, train_loss_epoch=362.0]
Epoch 31:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=659.0, train_loss_epoch=659.0]
Epoch 36:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=556.0, train_loss_epoch=556.0]
Epoch 41:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=685.0, train_loss_epoch=685.0]
Epoch 46:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=790.0, train_loss_epoch=790.0]
Epoch 51:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=692.0, train_loss_epoch=692.0]
Epoch 56:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=813.0, train_loss_epoch=813.0]
Epoch 60:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=886.0, train_loss_epoch=886.0]
Epoch 63:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=856.0, train_loss_epoch=856.0]
Epoch 66:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=314.0, train_loss_epoch=314.0]
Epoch 70:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=483.0, train_loss_epoch=483.0]
Epoch 73:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=549.0, train_loss_epoch=549.0]
Epoch 77:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=291.0, train_loss_epoch=291.0]
Epoch 80:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=745.0, train_loss_epoch=745.0]
Epoch 80: 100%|██████████| 1/1 [00:00<00:00, 41.33it/s, v_num=0, train_loss_step=823.0, train_loss_epoch=823.0]
Epoch 81:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=823.0, train_loss_epoch=823.0]
Epoch 84:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=857.0, train_loss_epoch=857.0]
Epoch 88:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=866.0, train_loss_epoch=866.0]
Epoch 91:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=643.0, train_loss_epoch=643.0]
Epoch 95:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=768.0, train_loss_epoch=768.0]
Epoch 98: 100%|██████████| 1/1 [00:00<00:00, 36.90it/s, v_num=0, train_loss_step=695.0, train_loss_epoch=695.0]
Epoch 99:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=695.0, train_loss_epoch=695.0]
Epoch 99: 100%|██████████| 1/1 [00:00<00:00, 30.86it/s, v_num=0, train_loss_step=525.0, train_loss_epoch=695.0]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 119.97it/s]
Epoch 101:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=325.0, train_loss_epoch=325.0, valid_loss=5.32e+7]
Epoch 104:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=238.0, train_loss_epoch=238.0, valid_loss=5.32e+7]
Epoch 107:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=449.0, train_loss_epoch=449.0, valid_loss=5.32e+7]
Epoch 111: 100%|██████████| 1/1 [00:00<00:00, 40.36it/s, v_num=0, train_loss_step=808.0, train_loss_epoch=808.0, valid_loss=5.32e+7]
Epoch 115:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=787.0, train_loss_epoch=787.0, valid_loss=5.32e+7]
Epoch 119:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=416.0, train_loss_epoch=416.0, valid_loss=5.32e+7]
Epoch 122:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=756.0, train_loss_epoch=756.0, valid_loss=5.32e+7]
Epoch 126:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=800.0, train_loss_epoch=800.0, valid_loss=5.32e+7]
Epoch 129:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=772.0, train_loss_epoch=772.0, valid_loss=5.32e+7]
Epoch 133:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=287.0, train_loss_epoch=287.0, valid_loss=5.32e+7]
Epoch 136:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=299.0, train_loss_epoch=299.0, valid_loss=5.32e+7]
Epoch 138:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=260.0, train_loss_epoch=260.0, valid_loss=5.32e+7]
Epoch 141:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=760.0, train_loss_epoch=760.0, valid_loss=5.32e+7]
Epoch 145:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=744.0, train_loss_epoch=744.0, valid_loss=5.32e+7]
Epoch 148:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=581.0, train_loss_epoch=581.0, valid_loss=5.32e+7]
Epoch 152:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=846.0, train_loss_epoch=846.0, valid_loss=5.32e+7]
Epoch 155:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=296.0, train_loss_epoch=296.0, valid_loss=5.32e+7]
Epoch 158:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=467.0, train_loss_epoch=467.0, valid_loss=5.32e+7]
Epoch 161:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=809.0, train_loss_epoch=809.0, valid_loss=5.32e+7]
Epoch 165:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=525.0, train_loss_epoch=525.0, valid_loss=5.32e+7]
Epoch 168:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=642.0, train_loss_epoch=642.0, valid_loss=5.32e+7]
Epoch 169:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=404.0, train_loss_epoch=404.0, valid_loss=5.32e+7]
Epoch 171:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=767.0, train_loss_epoch=767.0, valid_loss=5.32e+7]
Epoch 174:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=331.0, train_loss_epoch=331.0, valid_loss=5.32e+7]
Epoch 177:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=702.0, train_loss_epoch=702.0, valid_loss=5.32e+7]
Epoch 179:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=739.0, train_loss_epoch=739.0, valid_loss=5.32e+7]
Epoch 182:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=292.0, train_loss_epoch=292.0, valid_loss=5.32e+7]
Epoch 186:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=763.0, train_loss_epoch=763.0, valid_loss=5.32e+7]
Epoch 191:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=704.0, train_loss_epoch=704.0, valid_loss=5.32e+7]
Epoch 196:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=753.0, train_loss_epoch=753.0, valid_loss=5.32e+7]
Epoch 199: 100%|██████████| 1/1 [00:00<00:00, 53.82it/s, v_num=0, train_loss_step=301.0, train_loss_epoch=781.0, valid_loss=5.32e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 143.65it/s]
Epoch 199: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s, v_num=0, train_loss_step=301.0, train_loss_epoch=781.0, valid_loss=2.33e+7]
Epoch 199: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s, v_num=0, train_loss_step=301.0, train_loss_epoch=301.0, valid_loss=2.33e+7]
Epoch 204:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=712.0, train_loss_epoch=712.0, valid_loss=2.33e+7]
Epoch 208:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=661.0, train_loss_epoch=661.0, valid_loss=2.33e+7]
Epoch 212:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=438.0, train_loss_epoch=438.0, valid_loss=2.33e+7]
Epoch 217:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=306.0, train_loss_epoch=306.0, valid_loss=2.33e+7]
Epoch 221:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=389.0, train_loss_epoch=389.0, valid_loss=2.33e+7]
Epoch 221: 100%|██████████| 1/1 [00:00<00:00, 46.36it/s, v_num=0, train_loss_step=389.0, train_loss_epoch=389.0, valid_loss=2.33e+7]
Epoch 222:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=326.0, train_loss_epoch=326.0, valid_loss=2.33e+7]
Epoch 226:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=643.0, train_loss_epoch=643.0, valid_loss=2.33e+7]
Epoch 231:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=287.0, train_loss_epoch=287.0, valid_loss=2.33e+7]
Epoch 235:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=731.0, train_loss_epoch=731.0, valid_loss=2.33e+7]
Epoch 235: 100%|██████████| 1/1 [00:00<00:00, 42.76it/s, v_num=0, train_loss_step=731.0, train_loss_epoch=731.0, valid_loss=2.33e+7]
Epoch 236:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=286.0, train_loss_epoch=286.0, valid_loss=2.33e+7]
Epoch 241:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=590.0, train_loss_epoch=590.0, valid_loss=2.33e+7]
Epoch 245:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=602.0, train_loss_epoch=602.0, valid_loss=2.33e+7]
Epoch 250:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=387.0, train_loss_epoch=387.0, valid_loss=2.33e+7]
Epoch 253:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=483.0, train_loss_epoch=483.0, valid_loss=2.33e+7]
Epoch 254:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=505.0, train_loss_epoch=505.0, valid_loss=2.33e+7]
Epoch 258:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=704.0, train_loss_epoch=704.0, valid_loss=2.33e+7]
Epoch 263:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=687.0, train_loss_epoch=687.0, valid_loss=2.33e+7]
Epoch 268:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=308.0, train_loss_epoch=308.0, valid_loss=2.33e+7]
Epoch 272: 100%|██████████| 1/1 [00:00<00:00, 48.87it/s, v_num=0, train_loss_step=469.0, train_loss_epoch=469.0, valid_loss=2.33e+7]
Epoch 273:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=819.0, train_loss_epoch=819.0, valid_loss=2.33e+7]
Epoch 277:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=331.0, train_loss_epoch=331.0, valid_loss=2.33e+7]
Epoch 282:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=313.0, train_loss_epoch=313.0, valid_loss=2.33e+7]
Epoch 286:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=850.0, train_loss_epoch=850.0, valid_loss=2.33e+7]
Epoch 291:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=368.0, train_loss_epoch=368.0, valid_loss=2.33e+7]
Epoch 295:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=798.0, train_loss_epoch=798.0, valid_loss=2.33e+7]
Epoch 299:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=774.0, train_loss_epoch=774.0, valid_loss=2.33e+7]
Epoch 299: 100%|██████████| 1/1 [00:00<00:00, 37.70it/s, v_num=0, train_loss_step=661.0, train_loss_epoch=774.0, valid_loss=2.33e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 161.84it/s]
Epoch 303:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=749.0, train_loss_epoch=749.0, valid_loss=9.87e+7]
Epoch 307:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=737.0, train_loss_epoch=737.0, valid_loss=9.87e+7]
Epoch 312:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=305.0, train_loss_epoch=305.0, valid_loss=9.87e+7]
Epoch 316:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=526.0, train_loss_epoch=526.0, valid_loss=9.87e+7]
Epoch 320:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=536.0, train_loss_epoch=536.0, valid_loss=9.87e+7]
Epoch 324:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=569.0, train_loss_epoch=569.0, valid_loss=9.87e+7]
Epoch 329:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=678.0, train_loss_epoch=678.0, valid_loss=9.87e+7]
Epoch 334:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=520.0, train_loss_epoch=520.0, valid_loss=9.87e+7]
Epoch 338:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=434.0, train_loss_epoch=434.0, valid_loss=9.87e+7]
Epoch 343:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=919.0, train_loss_epoch=919.0, valid_loss=9.87e+7]
Epoch 347:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=630.0, train_loss_epoch=630.0, valid_loss=9.87e+7]
Epoch 352:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=327.0, train_loss_epoch=327.0, valid_loss=9.87e+7]
Epoch 357:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=514.0, train_loss_epoch=514.0, valid_loss=9.87e+7]
Epoch 362:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=323.0, train_loss_epoch=323.0, valid_loss=9.87e+7]
Epoch 367:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=675.0, train_loss_epoch=675.0, valid_loss=9.87e+7]
Epoch 372:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=765.0, train_loss_epoch=765.0, valid_loss=9.87e+7]
Epoch 377:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=764.0, train_loss_epoch=764.0, valid_loss=9.87e+7]
Epoch 381:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=539.0, train_loss_epoch=539.0, valid_loss=9.87e+7]
Epoch 385:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=646.0, train_loss_epoch=646.0, valid_loss=9.87e+7]
Epoch 390:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=337.0, train_loss_epoch=337.0, valid_loss=9.87e+7]
Epoch 394:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=679.0, train_loss_epoch=679.0, valid_loss=9.87e+7]
Epoch 394: 100%|██████████| 1/1 [00:00<00:00, 50.33it/s, v_num=0, train_loss_step=750.0, train_loss_epoch=679.0, valid_loss=9.87e+7]
Epoch 395:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=750.0, train_loss_epoch=750.0, valid_loss=9.87e+7]
Epoch 399:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=658.0, train_loss_epoch=658.0, valid_loss=9.87e+7]
Epoch 399: 100%|██████████| 1/1 [00:00<00:00, 35.19it/s, v_num=0, train_loss_step=418.0, train_loss_epoch=658.0, valid_loss=9.87e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 140.11it/s]
Epoch 403:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=651.0, train_loss_epoch=651.0, valid_loss=4.15e+7]
Epoch 408:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=670.0, train_loss_epoch=670.0, valid_loss=4.15e+7]
Epoch 408: 100%|██████████| 1/1 [00:00<00:00, 37.80it/s, v_num=0, train_loss_step=164.0, train_loss_epoch=164.0, valid_loss=4.15e+7]
Epoch 413:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=403.0, train_loss_epoch=403.0, valid_loss=4.15e+7]
Epoch 413: 100%|██████████| 1/1 [00:00<00:00, 52.11it/s, v_num=0, train_loss_step=544.0, train_loss_epoch=403.0, valid_loss=4.15e+7]
Epoch 414:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=544.0, train_loss_epoch=544.0, valid_loss=4.15e+7]
Epoch 418:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=424.0, train_loss_epoch=424.0, valid_loss=4.15e+7]
Epoch 419:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=424.0, train_loss_epoch=424.0, valid_loss=4.15e+7]
Epoch 424:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=641.0, train_loss_epoch=641.0, valid_loss=4.15e+7]
Epoch 429:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=799.0, train_loss_epoch=799.0, valid_loss=4.15e+7]
Epoch 433:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=593.0, train_loss_epoch=593.0, valid_loss=4.15e+7]
Epoch 437: 100%|██████████| 1/1 [00:00<00:00, 44.21it/s, v_num=0, train_loss_step=402.0, train_loss_epoch=402.0, valid_loss=4.15e+7]
Epoch 438:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=402.0, train_loss_epoch=402.0, valid_loss=4.15e+7]
Epoch 443:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=615.0, train_loss_epoch=615.0, valid_loss=4.15e+7]
Epoch 448:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=719.0, train_loss_epoch=719.0, valid_loss=4.15e+7]
Epoch 452:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=343.0, train_loss_epoch=343.0, valid_loss=4.15e+7]
Epoch 457:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=768.0, train_loss_epoch=768.0, valid_loss=4.15e+7]
Epoch 462:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=640.0, train_loss_epoch=640.0, valid_loss=4.15e+7]
Epoch 467:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=436.0, train_loss_epoch=436.0, valid_loss=4.15e+7]
Epoch 472:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=402.0, train_loss_epoch=402.0, valid_loss=4.15e+7]
Epoch 477:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=681.0, train_loss_epoch=681.0, valid_loss=4.15e+7]
Epoch 481:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=174.0, train_loss_epoch=174.0, valid_loss=4.15e+7]
Epoch 485: 100%|██████████| 1/1 [00:00<00:00, 48.66it/s, v_num=0, train_loss_step=205.0, train_loss_epoch=413.0, valid_loss=4.15e+7]
Epoch 490:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=532.0, train_loss_epoch=532.0, valid_loss=4.15e+7]
Epoch 494: 100%|██████████| 1/1 [00:00<00:00, 47.00it/s, v_num=0, train_loss_step=816.0, train_loss_epoch=611.0, valid_loss=4.15e+7]
Epoch 495:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=816.0, train_loss_epoch=816.0, valid_loss=4.15e+7]
Epoch 499:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=524.0, train_loss_epoch=524.0, valid_loss=4.15e+7]
Epoch 499: 100%|██████████| 1/1 [00:00<00:00, 47.44it/s, v_num=0, train_loss_step=406.0, train_loss_epoch=524.0, valid_loss=4.15e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 127.93it/s]
Epoch 502: 100%|██████████| 1/1 [00:00<00:00, 42.36it/s, v_num=0, train_loss_step=445.0, train_loss_epoch=400.0, valid_loss=2.65e+7]
Epoch 502: 100%|██████████| 1/1 [00:00<00:00, 37.81it/s, v_num=0, train_loss_step=445.0, train_loss_epoch=445.0, valid_loss=2.65e+7]
Epoch 503:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=445.0, train_loss_epoch=445.0, valid_loss=2.65e+7]
Epoch 507:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=609.0, train_loss_epoch=609.0, valid_loss=2.65e+7]
Epoch 511:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=663.0, train_loss_epoch=663.0, valid_loss=2.65e+7]
Epoch 516:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=755.0, train_loss_epoch=755.0, valid_loss=2.65e+7]
Epoch 520:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=629.0, train_loss_epoch=629.0, valid_loss=2.65e+7]
Epoch 520: 100%|██████████| 1/1 [00:00<00:00, 29.12it/s, v_num=0, train_loss_step=620.0, train_loss_epoch=620.0, valid_loss=2.65e+7]
Epoch 521:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=620.0, train_loss_epoch=620.0, valid_loss=2.65e+7]

(_train_tune pid=7530) `Trainer.fit` stopped: `max_steps=1000` reached.

(_train_tune pid=7530)
Epoch 999: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s, v_num=0, train_loss_step=804.0, train_loss_epoch=804.0, valid_loss=1.09e+8]

(_train_tune pid=7768) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=7768) Seed set to 13
(_train_tune pid=7768) GPU available: True (cuda), used: True
(_train_tune pid=7768) TPU available: False, using: 0 TPU cores
(_train_tune pid=7768) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=7768)
(_train_tune pid=7768)   | Name         | Type              | Params | Mode
(_train_tune pid=7768) -----------------------------------------------------------
(_train_tune pid=7768) 0 | loss         | MAE               | 0      | train
(_train_tune pid=7768) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=7768) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=7768) 3 | model        | PatchTST_backbone | 400 K  | train
(_train_tune pid=7768) -----------------------------------------------------------
(_train_tune pid=7768) 400 K     Trainable params
(_train_tune pid=7768) 3         Non-trainable params
(_train_tune pid=7768) 400 K     Total params
(_train_tune pid=7768) 1.603     Total estimated model params size (MB)
(_train_tune pid=7768) 89        Modules in train mode
(_train_tune pid=7768) 0         Modules in eval mode
(_train_tune pid=7768) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 3:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.41e+7, train_loss_epoch=3.41e+7]
Epoch 8:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.25e+7, train_loss_epoch=2.25e+7]
Epoch 13:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.41e+7, train_loss_epoch=2.41e+7]
Epoch 17:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.26e+7, train_loss_epoch=1.26e+7]
Epoch 21:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.25e+7, train_loss_epoch=1.25e+7]
Epoch 21: 100%|██████████| 1/1 [00:00<00:00, 39.81it/s, v_num=0, train_loss_step=1.08e+7, train_loss_epoch=1.08e+7]
Epoch 26:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.44e+7, train_loss_epoch=3.44e+7]
Epoch 31:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.56e+7, train_loss_epoch=3.56e+7]
Epoch 35:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.31e+7, train_loss_epoch=1.31e+7]
Epoch 40:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.29e+7, train_loss_epoch=1.29e+7]
Epoch 45:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.45e+7, train_loss_epoch=2.45e+7]
Epoch 49:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.22e+7, train_loss_epoch=1.22e+7]
Epoch 54:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.38e+7, train_loss_epoch=3.38e+7]
Epoch 59:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=8.34e+6, train_loss_epoch=8.34e+6]
Epoch 63:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.54e+7, train_loss_epoch=2.54e+7]
Epoch 68:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.61e+7, train_loss_epoch=1.61e+7]
Epoch 69:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.61e+7, train_loss_epoch=1.61e+7]
Epoch 74:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.78e+7, train_loss_epoch=3.78e+7]
Epoch 79:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.23e+7, train_loss_epoch=2.23e+7]
Epoch 84:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.74e+7, train_loss_epoch=3.74e+7]
Epoch 84: 100%|██████████| 1/1 [00:00<00:00, 53.11it/s, v_num=0, train_loss_step=2.17e+7, train_loss_epoch=3.74e+7]
Epoch 84:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.17e+7, train_loss_epoch=2.17e+7]
Epoch 85:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.17e+7, train_loss_epoch=2.17e+7]
Epoch 90:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.83e+7, train_loss_epoch=1.83e+7]
Epoch 95: 100%|██████████| 1/1 [00:00<00:00, 58.92it/s, v_num=0, train_loss_step=3.86e+7, train_loss_epoch=2.07e+7]
Epoch 96:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.86e+7, train_loss_epoch=3.86e+7]
Epoch 99: 100%|██████████| 1/1 [00:00<00:00, 53.17it/s, v_num=0, train_loss_step=1.64e+7, train_loss_epoch=7.36e+6]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 192.35it/s]
(_train_tune pid=7768)
Epoch 99: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s, v_num=0, train_loss_step=1.64e+7, train_loss_epoch=1.64e+7, valid_loss=3.11e+7]
Epoch 104:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.89e+7, train_loss_epoch=2.89e+7, valid_loss=3.11e+7]
Epoch 104: 100%|██████████| 1/1 [00:00<00:00, 56.98it/s, v_num=0, train_loss_step=1.54e+7, train_loss_epoch=2.89e+7, valid_loss=3.11e+7]
Epoch 104:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.54e+7, train_loss_epoch=1.54e+7, valid_loss=3.11e+7]
Epoch 105:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.54e+7, train_loss_epoch=1.54e+7, valid_loss=3.11e+7]
Epoch 109: 100%|██████████| 1/1 [00:00<00:00, 36.24it/s, v_num=0, train_loss_step=1.59e+6, train_loss_epoch=1.59e+6, valid_loss=3.11e+7]
Epoch 110:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.59e+6, train_loss_epoch=1.59e+6, valid_loss=3.11e+7]
Epoch 114:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.38e+7, train_loss_epoch=3.38e+7, valid_loss=3.11e+7]
Epoch 119:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.23e+7, train_loss_epoch=3.23e+7, valid_loss=3.11e+7]
Epoch 124:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.93e+7, train_loss_epoch=4.93e+7, valid_loss=3.11e+7]
Epoch 129:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.12e+7, train_loss_epoch=2.12e+7, valid_loss=3.11e+7]
Epoch 134:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.49e+7, train_loss_epoch=2.49e+7, valid_loss=3.11e+7]
Epoch 139:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.9e+7, train_loss_epoch=1.9e+7, valid_loss=3.11e+7]
Epoch 140:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.77e+7, train_loss_epoch=2.77e+7, valid_loss=3.11e+7]
Epoch 145:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.56e+7, train_loss_epoch=2.56e+7, valid_loss=3.11e+7]
Epoch 149:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.06e+7, train_loss_epoch=2.06e+7, valid_loss=3.11e+7]
Epoch 149: 100%|██████████| 1/1 [00:00<00:00, 46.93it/s, v_num=0, train_loss_step=2.18e+7, train_loss_epoch=2.06e+7, valid_loss=3.11e+7]
Epoch 149: 100%|██████████| 1/1 [00:00<00:00, 39.94it/s, v_num=0, train_loss_step=2.18e+7, train_loss_epoch=2.18e+7, valid_loss=3.11e+7]
Epoch 150:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.18e+7, train_loss_epoch=2.18e+7, valid_loss=3.11e+7]
Epoch 155:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.54e+7, train_loss_epoch=2.54e+7, valid_loss=3.11e+7]
Epoch 159:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.49e+7, train_loss_epoch=1.49e+7, valid_loss=3.11e+7]
Epoch 164:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.6e+7, train_loss_epoch=2.6e+7, valid_loss=3.11e+7]
Epoch 164: 100%|██████████| 1/1 [00:00<00:00, 56.66it/s, v_num=0, train_loss_step=2.79e+7, train_loss_epoch=2.6e+7, valid_loss=3.11e+7]
Epoch 164: 100%|██████████| 1/1 [00:00<00:00, 50.22it/s, v_num=0, train_loss_step=2.79e+7, train_loss_epoch=2.79e+7, valid_loss=3.11e+7]
Epoch 165:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.79e+7, train_loss_epoch=2.79e+7, valid_loss=3.11e+7]
Epoch 170:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.74e+7, train_loss_epoch=1.74e+7, valid_loss=3.11e+7]
Epoch 175:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.53e+7, train_loss_epoch=4.53e+7, valid_loss=3.11e+7]
Epoch 180:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.13e+6, train_loss_epoch=4.13e+6, valid_loss=3.11e+7]
Epoch 184: 100%|██████████| 1/1 [00:00<00:00, 51.68it/s, v_num=0, train_loss_step=3.35e+7, train_loss_epoch=3.35e+7, valid_loss=3.11e+7]
Epoch 185:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.35e+7, train_loss_epoch=3.35e+7, valid_loss=3.11e+7]
Epoch 189:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.51e+7, train_loss_epoch=1.51e+7, valid_loss=3.11e+7]
Epoch 194:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.4e+6, train_loss_epoch=4.4e+6, valid_loss=3.11e+7]
Epoch 199:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.98e+6, train_loss_epoch=3.98e+6, valid_loss=3.11e+7]
Epoch 199: 100%|██████████| 1/1 [00:00<00:00, 47.56it/s, v_num=0, train_loss_step=2.66e+7, train_loss_epoch=3.98e+6, valid_loss=3.11e+7]
(_train_tune pid=7768)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 154.38it/s]
Epoch 203: 100%|██████████| 1/1 [00:00<00:00, 56.51it/s, v_num=0, train_loss_step=9.5e+6, train_loss_epoch=9.5e+6, valid_loss=3.11e+7]
Epoch 204:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=9.5e+6, train_loss_epoch=9.5e+6, valid_loss=3.11e+7]
Epoch 208:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.15e+7, train_loss_epoch=3.15e+7, valid_loss=3.11e+7]
Epoch 213:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.37e+6, train_loss_epoch=7.37e+6, valid_loss=3.11e+7]
Epoch 217:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.94e+7, train_loss_epoch=1.94e+7, valid_loss=3.11e+7]
Epoch 222:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.82e+7, train_loss_epoch=1.82e+7, valid_loss=3.11e+7]
Epoch 226: 100%|██████████| 1/1 [00:00<00:00, 40.61it/s, v_num=0, train_loss_step=2.41e+7, train_loss_epoch=2.41e+7, valid_loss=3.11e+7]
Epoch 226: 100%|██████████| 1/1 [00:00<00:00, 39.76it/s, v_num=0, train_loss_step=1.77e+7, train_loss_epoch=2.41e+7, valid_loss=3.11e+7]
Epoch 226: 100%|██████████| 1/1 [00:00<00:00, 38.56it/s, v_num=0, train_loss_step=1.77e+7, train_loss_epoch=1.77e+7, valid_loss=3.11e+7]
Epoch 227:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.77e+7, train_loss_epoch=1.77e+7, valid_loss=3.11e+7]
Epoch 231: 100%|██████████| 1/1 [00:00<00:00, 51.58it/s, v_num=0, train_loss_step=3.83e+7, train_loss_epoch=3.83e+7, valid_loss=3.11e+7]
Epoch 232:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.83e+7, train_loss_epoch=3.83e+7, valid_loss=3.11e+7]
Epoch 236:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.35e+7, train_loss_epoch=1.35e+7, valid_loss=3.11e+7]
Epoch 241:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.35e+7, train_loss_epoch=3.35e+7, valid_loss=3.11e+7]
Epoch 246:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.92e+7, train_loss_epoch=2.92e+7, valid_loss=3.11e+7]
Epoch 251:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.13e+7, train_loss_epoch=3.13e+7, valid_loss=3.11e+7]
Epoch 255:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=5.58e+6, train_loss_epoch=5.58e+6, valid_loss=3.11e+7]
Epoch 259: 100%|██████████| 1/1 [00:00<00:00, 51.40it/s, v_num=0, train_loss_step=1.58e+7, train_loss_epoch=1.58e+7, valid_loss=3.11e+7]
Epoch 264:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.21e+7, train_loss_epoch=1.21e+7, valid_loss=3.11e+7]
Epoch 269:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.83e+7, train_loss_epoch=2.83e+7, valid_loss=3.11e+7]
Epoch 274: 100%|██████████| 1/1 [00:00<00:00, 49.39it/s, v_num=0, train_loss_step=1.73e+7, train_loss_epoch=1.73e+7, valid_loss=3.11e+7]
Epoch 280:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.21e+7, train_loss_epoch=3.21e+7, valid_loss=3.11e+7]
Epoch 284: 100%|██████████| 1/1 [00:00<00:00, 52.12it/s, v_num=0, train_loss_step=2.48e+7, train_loss_epoch=2.48e+7, valid_loss=3.11e+7]
Epoch 285:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.48e+7, train_loss_epoch=2.48e+7, valid_loss=3.11e+7]
Epoch 289: 100%|██████████| 1/1 [00:00<00:00, 54.64it/s, v_num=0, train_loss_step=1.45e+7, train_loss_epoch=4.23e+7, valid_loss=3.11e+7]
Epoch 290:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.45e+7, train_loss_epoch=1.45e+7, valid_loss=3.11e+7]
Epoch 295:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.64e+7, train_loss_epoch=2.64e+7, valid_loss=3.11e+7]
Epoch 299:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.98e+7, train_loss_epoch=2.98e+7, valid_loss=3.11e+7]
Epoch 299: 100%|██████████| 1/1 [00:00<00:00, 29.13it/s, v_num=0, train_loss_step=5.81e+6, train_loss_epoch=2.98e+7, valid_loss=3.11e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 107.93it/s]
Epoch 303:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.13e+7, train_loss_epoch=1.13e+7, valid_loss=3.11e+7]
Epoch 307:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.63e+7, train_loss_epoch=2.63e+7, valid_loss=3.11e+7]
Epoch 307: 100%|██████████| 1/1 [00:00<00:00, 45.61it/s, v_num=0, train_loss_step=2.92e+7, train_loss_epoch=2.92e+7, valid_loss=3.11e+7]
Epoch 308:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.92e+7, train_loss_epoch=2.92e+7, valid_loss=3.11e+7]
Epoch 312:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.76e+7, train_loss_epoch=1.76e+7, valid_loss=3.11e+7]
Epoch 316: 100%|██████████| 1/1 [00:00<00:00, 49.24it/s, v_num=0, train_loss_step=2.68e+7, train_loss_epoch=2.68e+7, valid_loss=3.11e+7]
Epoch 317:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.68e+7, train_loss_epoch=2.68e+7, valid_loss=3.11e+7]
Epoch 321:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.14e+7, train_loss_epoch=2.14e+7, valid_loss=3.11e+7]
Epoch 326:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.89e+7, train_loss_epoch=1.89e+7, valid_loss=3.11e+7]
Epoch 331:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.58e+7, train_loss_epoch=1.58e+7, valid_loss=3.11e+7]
Epoch 336:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.72e+7, train_loss_epoch=2.72e+7, valid_loss=3.11e+7]
Epoch 341:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.28e+7, train_loss_epoch=1.28e+7, valid_loss=3.11e+7]
Epoch 341: 100%|██████████| 1/1 [00:00<00:00, 42.07it/s, v_num=0, train_loss_step=3.46e+7, train_loss_epoch=1.28e+7, valid_loss=3.11e+7]
Epoch 342:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.46e+7, train_loss_epoch=3.46e+7, valid_loss=3.11e+7]
Epoch 346:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.7e+7, train_loss_epoch=1.7e+7, valid_loss=3.11e+7]
Epoch 350:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.14e+7, train_loss_epoch=1.14e+7, valid_loss=3.11e+7]
Epoch 355:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.72e+7, train_loss_epoch=3.72e+7, valid_loss=3.11e+7]
Epoch 360:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.73e+7, train_loss_epoch=1.73e+7, valid_loss=3.11e+7]
Epoch 365: 100%|██████████| 1/1 [00:00<00:00, 56.89it/s, v_num=0, train_loss_step=1.8e+7, train_loss_epoch=1.8e+7, valid_loss=3.11e+7]
Epoch 366:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.8e+7, train_loss_epoch=1.8e+7, valid_loss=3.11e+7]
Epoch 371:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.13e+7, train_loss_epoch=2.13e+7, valid_loss=3.11e+7]
Epoch 376:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.76e+7, train_loss_epoch=1.76e+7, valid_loss=3.11e+7]
Epoch 381:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.42e+7, train_loss_epoch=3.42e+7, valid_loss=3.11e+7]
Epoch 385: 100%|██████████| 1/1 [00:00<00:00, 58.33it/s, v_num=0, train_loss_step=6.71e+6, train_loss_epoch=6.71e+6, valid_loss=3.11e+7]
Epoch 386:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=6.71e+6, train_loss_epoch=6.71e+6, valid_loss=3.11e+7]
Epoch 391:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.79e+7, train_loss_epoch=2.79e+7, valid_loss=3.11e+7]
Epoch 393:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.36e+7, train_loss_epoch=1.36e+7, valid_loss=3.11e+7]
Epoch 396:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.44e+7, train_loss_epoch=3.44e+7, valid_loss=3.11e+7]
Epoch 399:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.54e+7, train_loss_epoch=2.54e+7, valid_loss=3.11e+7]
Epoch 399: 100%|██████████| 1/1 [00:00<00:00, 33.01it/s, v_num=0, train_loss_step=5.51e+6, train_loss_epoch=2.54e+7, valid_loss=3.11e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 119.84it/s]
Epoch 401:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.52e+7, train_loss_epoch=3.52e+7, valid_loss=3.11e+7]
Epoch 405:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.29e+7, train_loss_epoch=2.29e+7, valid_loss=3.11e+7]
Epoch 408:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=7.42e+6, train_loss_epoch=7.42e+6, valid_loss=3.11e+7]
Epoch 411: 100%|██████████| 1/1 [00:00<00:00, 41.80it/s, v_num=0, train_loss_step=3.72e+7, train_loss_epoch=3.72e+7, valid_loss=3.11e+7]
Epoch 414:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.77e+7, train_loss_epoch=1.77e+7, valid_loss=3.11e+7]
Epoch 417:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.43e+7, train_loss_epoch=1.43e+7, valid_loss=3.11e+7]
Epoch 421:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.8e+7, train_loss_epoch=2.8e+7, valid_loss=3.11e+7]
Epoch 424:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.08e+7, train_loss_epoch=2.08e+7, valid_loss=3.11e+7]
Epoch 427:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.17e+7, train_loss_epoch=2.17e+7, valid_loss=3.11e+7]
Epoch 430: 100%|██████████| 1/1 [00:00<00:00, 45.81it/s, v_num=0, train_loss_step=2.05e+7, train_loss_epoch=2.05e+7, valid_loss=3.11e+7]
Epoch 435:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.16e+7, train_loss_epoch=1.16e+7, valid_loss=3.11e+7]
Epoch 439:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.92e+7, train_loss_epoch=1.92e+7, valid_loss=3.11e+7]
Epoch 443:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.68e+7, train_loss_epoch=1.68e+7, valid_loss=3.11e+7]
Epoch 446:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.06e+7, train_loss_epoch=2.06e+7, valid_loss=3.11e+7]
Epoch 450:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.04e+7, train_loss_epoch=1.04e+7, valid_loss=3.11e+7]
Epoch 454:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=6.35e+6, train_loss_epoch=6.35e+6, valid_loss=3.11e+7]
Epoch 457:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.46e+7, train_loss_epoch=1.46e+7, valid_loss=3.11e+7]
Epoch 458:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.46e+7, train_loss_epoch=1.46e+7, valid_loss=3.11e+7]
Epoch 461:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.68e+6, train_loss_epoch=2.68e+6, valid_loss=3.11e+7]
Epoch 465:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.07e+7, train_loss_epoch=1.07e+7, valid_loss=3.11e+7]
Epoch 469:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.27e+7, train_loss_epoch=3.27e+7, valid_loss=3.11e+7]
Epoch 473:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.85e+7, train_loss_epoch=1.85e+7, valid_loss=3.11e+7]
Epoch 476:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=4.29e+7, train_loss_epoch=4.29e+7, valid_loss=3.11e+7]
Epoch 481:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.62e+7, train_loss_epoch=1.62e+7, valid_loss=3.11e+7]
Epoch 485:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.56e+7, train_loss_epoch=3.56e+7, valid_loss=3.11e+7]
Epoch 489:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.38e+7, train_loss_epoch=1.38e+7, valid_loss=3.11e+7]
Epoch 492:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=1.02e+7, train_loss_epoch=1.02e+7, valid_loss=3.11e+7]
Epoch 496:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=2.32e+7, train_loss_epoch=2.32e+7, valid_loss=3.11e+7]
Epoch 499:   0%|          | 0/1 [00:00<?, ?it/s, v_num=0, train_loss_step=3.18e+7, train_loss_epoch=3.18e+7, valid_loss=3.11e+7]

(_train_tune pid=7768) `Trainer.fit` stopped: `max_steps=1000` reached.

(_train_tune pid=7768)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 171.89it/s]
Epoch 999: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s, v_num=0, train_loss_step=1.76e+7, train_loss_epoch=1.76e+7, valid_loss=3.11e+7]

(_train_tune pid=8002) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8002) Seed set to 13
(_train_tune pid=8002) GPU available: True (cuda), used: True
(_train_tune pid=8002) TPU available: False, using: 0 TPU cores
(_train_tune pid=8002) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=8002)
(_train_tune pid=8002)   | Name         | Type              | Params | Mode
(_train_tune pid=8002) -----------------------------------------------------------
(_train_tune pid=8002) 0 | loss         | MAE               | 0      | train
(_train_tune pid=8002) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=8002) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=8002) 3 | model        | PatchTST_backbone | 1.2 M  | train
(_train_tune pid=8002) -----------------------------------------------------------
(_train_tune pid=8002) 1.2 M     Trainable params
(_train_tune pid=8002) 3         Non-trainable params
(_train_tune pid=8002) 1.2 M     Total params
(_train_tune pid=8002) 4.776     Total estimated model params size (MB)
(_train_tune pid=8002) 89        Modules in train mode
(_train_tune pid=8002) 0         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]

(_train_tune pid=8002) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Epoch 0:   0%|          | 0/6 [00:00<?, ?it/s]
Epoch 1:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.210, train_loss_epoch=471.0]
Epoch 2:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.460, train_loss_epoch=411.0]
Epoch 3:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.53e+3, train_loss_epoch=479.0]
Epoch 4:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.942, train_loss_epoch=411.0]
Epoch 5:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=20.20, train_loss_epoch=324.0]
Epoch 6:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.930, train_loss_epoch=418.0]
Epoch 7:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=340.0, train_loss_epoch=396.0]
Epoch 8:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.220, train_loss_epoch=506.0]
Epoch 9:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.220, train_loss_epoch=379.0]
Epoch 10:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.300, train_loss_epoch=524.0]
Epoch 11:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=373.0, train_loss_epoch=387.0]
Epoch 12:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.720, train_loss_epoch=342.0]
Epoch 13:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=681.0, train_loss_epoch=376.0]
Epoch 15:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.020, train_loss_epoch=414.0]
Epoch 16:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=14.60, train_loss_epoch=461.0]
(_train_tune pid=8002)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 162.79it/s]
(_train_tune pid=8002)
Epoch 17:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.932, train_loss_epoch=360.0, valid_loss=2.32e+7]
Epoch 18:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=7.940, train_loss_epoch=524.0, valid_loss=2.32e+7]
Epoch 19:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.060, train_loss_epoch=319.0, valid_loss=2.32e+7]
Epoch 20:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=5.180, train_loss_epoch=346.0, valid_loss=2.32e+7]
Epoch 21:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=649.0, train_loss_epoch=411.0, valid_loss=2.32e+7]
Epoch 22:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=10.40, train_loss_epoch=364.0, valid_loss=2.32e+7]
Epoch 23:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=684.0, train_loss_epoch=403.0, valid_loss=2.32e+7]
Epoch 24:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=17.20, train_loss_epoch=303.0, valid_loss=2.32e+7]
Epoch 25:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.120, train_loss_epoch=317.0, valid_loss=2.32e+7]
Epoch 26:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.010, train_loss_epoch=339.0, valid_loss=2.32e+7]
Epoch 27:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=9.020, train_loss_epoch=429.0, valid_loss=2.32e+7]
Epoch 28:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=712.0, train_loss_epoch=400.0, valid_loss=2.32e+7]
Epoch 29:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.030, train_loss_epoch=447.0, valid_loss=2.32e+7]
Epoch 30:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.930, train_loss_epoch=390.0, valid_loss=2.32e+7]
Epoch 31:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.000, train_loss_epoch=361.0, valid_loss=2.32e+7]
Epoch 32:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.360, train_loss_epoch=406.0, valid_loss=2.32e+7]
Epoch 33:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.510, train_loss_epoch=511.0, valid_loss=2.32e+7]
(_train_tune pid=8002)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 159.34it/s]
Epoch 33:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.280, train_loss_epoch=511.0, valid_loss=2.71e+7]
Epoch 34:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.510, train_loss_epoch=322.0, valid_loss=2.71e+7]
Epoch 35:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=367.0, train_loss_epoch=393.0, valid_loss=2.71e+7]
Epoch 36:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.610, train_loss_epoch=425.0, valid_loss=2.71e+7]
Epoch 37:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=667.0, train_loss_epoch=433.0, valid_loss=2.71e+7]
Epoch 38:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.28e+3, train_loss_epoch=420.0, valid_loss=2.71e+7]
Epoch 39:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=7.450, train_loss_epoch=430.0, valid_loss=2.71e+7]
Epoch 40:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=749.0, train_loss_epoch=370.0, valid_loss=2.71e+7]
Epoch 41:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=782.0, train_loss_epoch=439.0, valid_loss=2.71e+7]
Epoch 42:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.410, train_loss_epoch=405.0, valid_loss=2.71e+7]
Epoch 43:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.830, train_loss_epoch=327.0, valid_loss=2.71e+7]
Epoch 44:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=870.0, train_loss_epoch=412.0, valid_loss=2.71e+7]
Epoch 45:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=394.0, train_loss_epoch=282.0, valid_loss=2.71e+7]
Epoch 46:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=15.70, train_loss_epoch=294.0, valid_loss=2.71e+7]
Epoch 47:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.61e+3, train_loss_epoch=409.0, valid_loss=2.71e+7]
Epoch 48:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.816, train_loss_epoch=384.0, valid_loss=2.71e+7]
Epoch 49:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=474.0, train_loss_epoch=378.0, valid_loss=2.71e+7]
Epoch 49: 100%|██████████| 6/6 [00:00<00:00, 38.30it/s, v_num=0, train_loss_step=0.669, train_loss_epoch=378.0, valid_loss=2.71e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 132.00it/s]
(_train_tune pid=8002)
Epoch 49: 100%|██████████| 6/6 [00:00<00:00, 26.91it/s, v_num=0, train_loss_step=0.669, train_loss_epoch=378.0, valid_loss=2.69e+7]
Epoch 49: 100%|██████████| 6/6 [00:00<00:00, 26.72it/s, v_num=0, train_loss_step=0.669, train_loss_epoch=463.0, valid_loss=2.69e+7]
Epoch 50:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.669, train_loss_epoch=463.0, valid_loss=2.69e+7]
Epoch 51:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.010, train_loss_epoch=363.0, valid_loss=2.69e+7]
Epoch 52:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=364.0, train_loss_epoch=512.0, valid_loss=2.69e+7]
Epoch 52: 100%|██████████| 6/6 [00:00<00:00, 43.22it/s, v_num=0, train_loss_step=3.24e+3, train_loss_epoch=512.0, valid_loss=2.69e+7]
Epoch 53:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.24e+3, train_loss_epoch=624.0, valid_loss=2.69e+7]
Epoch 54:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=20.70, train_loss_epoch=392.0, valid_loss=2.69e+7]
Epoch 55:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.850, train_loss_epoch=348.0, valid_loss=2.69e+7]
Epoch 56:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.51e+3, train_loss_epoch=360.0, valid_loss=2.69e+7]
Epoch 57:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.570, train_loss_epoch=364.0, valid_loss=2.69e+7]
Epoch 58:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=640.0, train_loss_epoch=527.0, valid_loss=2.69e+7]
Epoch 59:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=478.0, train_loss_epoch=457.0, valid_loss=2.69e+7]
Epoch 60:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.700, train_loss_epoch=491.0, valid_loss=2.69e+7]
Epoch 61:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=6.070, train_loss_epoch=360.0, valid_loss=2.69e+7]
Epoch 62:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.070, train_loss_epoch=404.0, valid_loss=2.69e+7]
Epoch 63:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.270, train_loss_epoch=499.0, valid_loss=2.69e+7]
Epoch 64:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.56e+3, train_loss_epoch=524.0, valid_loss=2.69e+7]
Epoch 65:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=4.570, train_loss_epoch=362.0, valid_loss=2.69e+7]
Epoch 66:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=964.0, train_loss_epoch=295.0, valid_loss=2.69e+7]
(_train_tune pid=8002)
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 104.63it/s]
Epoch 66:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=586.0, train_loss_epoch=295.0, valid_loss=2.26e+7]
Epoch 67:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.736, train_loss_epoch=404.0, valid_loss=2.26e+7]
Epoch 67: 100%|██████████| 6/6 [00:00<00:00, 37.28it/s, v_num=0, train_loss_step=2.300, train_loss_epoch=404.0, valid_loss=2.26e+7]
Epoch 67: 100%|██████████| 6/6 [00:00<00:00, 37.10it/s, v_num=0, train_loss_step=2.300, train_loss_epoch=367.0, valid_loss=2.26e+7]
Epoch 68:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.300, train_loss_epoch=367.0, valid_loss=2.26e+7]
Epoch 69:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.83e+3, train_loss_epoch=428.0, valid_loss=2.26e+7]
Epoch 70:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.270, train_loss_epoch=379.0, valid_loss=2.26e+7]
Epoch 71:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=418.0, train_loss_epoch=390.0, valid_loss=2.26e+7]
Epoch 72:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=1.6e+3, train_loss_epoch=441.0, valid_loss=2.26e+7]
Epoch 73:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=3.600, train_loss_epoch=404.0, valid_loss=2.26e+7]
Epoch 74:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=0.742, train_loss_epoch=298.0, valid_loss=2.26e+7]
Epoch 75:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=495.0, train_loss_epoch=443.0, valid_loss=2.26e+7]
Epoch 76:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=362.0, train_loss_epoch=341.0, valid_loss=2.26e+7]
Epoch 77:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=575.0, train_loss_epoch=427.0, valid_loss=2.26e+7]
Epoch 77: 100%|██████████| 6/6 [00:00<00:00, 54.36it/s, v_num=0, train_loss_step=2.810, train_loss_epoch=427.0, valid_loss=2.26e+7]
Epoch 77: 100%|██████████| 6/6 [00:00<00:00, 53.31it/s, v_num=0, train_loss_step=2.810, train_loss_epoch=345.0, valid_loss=2.26e+7]
Epoch 78:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.810, train_loss_epoch=345.0, valid_loss=2.26e+7]
Epoch 79:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=510.0, train_loss_epoch=359.0, valid_loss=2.26e+7]
Epoch 80:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=441.0, train_loss_epoch=361.0, valid_loss=2.26e+7]
Epoch 81:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=854.0, train_loss_epoch=369.0, valid_loss=2.26e+7]
Epoch 82:   0%|          | 0/6 [00:00<?, ?it/s, v_num=0, train_loss_step=2.940, train_loss_epoch=422.0, valid_loss=2.26e+7]
Epoch 83: 100%|██████████| 2/2 [00:00<00:00, 63.80it/s, v_num=0, train_loss_step=334.0, train_loss_epoch=526.0, valid_loss=2.26e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/6 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 6/6 [00:00<00:00, 160.12it/s]
Epoch 83: 100%|██████████| 2/2 [00:00<00:00, 23.45it/s, v_num=0, train_loss_step=334.0, train_loss_epoch=167.0, valid_loss=2.14e+7]

(_train_tune pid=8002) `Trainer.fit` stopped: `max_steps=500` reached.
(_train_tune pid=8182) /usr/local/lib/python3.12/dist-packages/ray/tune/integration/pytorch_lightning.py:198: `ray.tune.integration.pytorch_lightning.TuneReportCallback` is deprecated. Use `ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback` instead.
(_train_tune pid=8182) Seed set to 14
(_train_tune pid=8182) GPU available: True (cuda), used: True
(_train_tune pid=8182) TPU available: False, using: 0 TPU cores
(_train_tune pid=8182) LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
(_train_tune pid=8182)
(_train_tune pid=8182)   | Name         | Type              | Params | Mode
(_train_tune pid=8182) -----------------------------------------------------------
(_train_tune pid=8182) 0 | loss         | MAE               | 0      | train
(_train_tune pid=8182) 1 | padder_train | ConstantPad1d     | 0      | train
(_train_tune pid=8182) 2 | scaler       | TemporalNorm      | 0      | train
(_train_tune pid=8182) 3 | model        | PatchTST_backbone | 1.2 M  | train
(_train_tune pid=8182) -----------------------------------------------------------
(_train_tune pid=8182) 1.2 M     Trainable params
(_train_tune pid=8182) 3         Non-trainable params
(_train_tune pid=8182) 1.2 M     Total params
(_train_tune pid=8182) 4.772     Total estimated model params size (MB)
(_train_tune pid=8182) 89        Modules in train mode
(_train_tune pid=8182) 0         Modules in eval mode
(_train_tune pid=8182) /usr/local/lib/python3.12/dist-packages/pytorch_lightning/utilities/_pytree.py:21: `isinstance(treespec, LeafSpec)` is deprecated, use `isinstance(treespec, TreeSpec) and treespec.is_leaf()` instead.

Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 1:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=220.0, train_loss_epoch=908.0]
Epoch 1: 100%|██████████| 2/2 [00:00<00:00, 59.89it/s, v_num=0, train_loss_step=3.2e+3, train_loss_epoch=908.0]
Epoch 2:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=3.2e+3, train_loss_epoch=1.93e+3]
Epoch 4:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=112.0, train_loss_epoch=524.0]
Epoch 4: 100%|██████████| 2/2 [00:00<00:00, 54.81it/s, v_num=0, train_loss_step=1.75e+3, train_loss_epoch=1.44e+3]
Epoch 7:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.32e+3, train_loss_epoch=1.48e+3]
Epoch 10:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=147.0, train_loss_epoch=898.0]
Epoch 12:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=33.90, train_loss_epoch=723.0]
Epoch 15:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=71.20, train_loss_epoch=776.0]
Epoch 17:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=335.0, train_loss_epoch=447.0]
Epoch 20:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.4e+3, train_loss_epoch=1.8e+3]
Epoch 22:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.24e+3, train_loss_epoch=1.21e+3]
Epoch 24:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=325.0, train_loss_epoch=672.0]
Epoch 25:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.77e+3, train_loss_epoch=1.11e+3]
Epoch 27:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=125.0, train_loss_epoch=289.0]
Epoch 29:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=3.560, train_loss_epoch=345.0]
Epoch 31:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=289.0, train_loss_epoch=1.15e+3]
Epoch 32:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.18e+3, train_loss_epoch=1.51e+3]
Epoch 34:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.11e+3, train_loss_epoch=1.45e+3]
Epoch 36:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=129.0, train_loss_epoch=970.0]
Epoch 38:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=120.0, train_loss_epoch=639.0]
Epoch 40:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.52e+3, train_loss_epoch=1.05e+3]
Epoch 42:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=341.0, train_loss_epoch=447.0]
Epoch 44:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=295.0, train_loss_epoch=1.16e+3]
Epoch 46:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=74.70, train_loss_epoch=522.0]
Epoch 48:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.03e+3, train_loss_epoch=1.23e+3]
Epoch 49:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=550.0, train_loss_epoch=486.0]
Epoch 49: 100%|██████████| 2/2 [00:00<00:00, 30.69it/s, v_num=0, train_loss_step=521.0, train_loss_epoch=486.0]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 2/2 [00:00<00:00, 62.71it/s]
Epoch 50:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=521.0, train_loss_epoch=659.0, valid_loss=2.27e+7]
Epoch 52:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=15.60, train_loss_epoch=918.0, valid_loss=2.27e+7]
Epoch 54:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=78.30, train_loss_epoch=1e+3, valid_loss=2.27e+7]
Epoch 56:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=335.0, train_loss_epoch=904.0, valid_loss=2.27e+7]
Epoch 58:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=381.0, train_loss_epoch=1.07e+3, valid_loss=2.27e+7]
Epoch 60:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.24e+3, train_loss_epoch=1.17e+3, valid_loss=2.27e+7]
Epoch 62:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.880, train_loss_epoch=313.0, valid_loss=2.27e+7]
Epoch 64:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=129.0, train_loss_epoch=1.03e+3, valid_loss=2.27e+7]
Epoch 66:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=800.0, train_loss_epoch=663.0, valid_loss=2.27e+7]
Epoch 68:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=659.0, train_loss_epoch=799.0, valid_loss=2.27e+7]
Epoch 69:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.48e+3, train_loss_epoch=809.0, valid_loss=2.27e+7]
Epoch 71:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=111.0, train_loss_epoch=1.18e+3, valid_loss=2.27e+7]
Epoch 72:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.01e+3, train_loss_epoch=767.0, valid_loss=2.27e+7]
Epoch 73:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=305.0, train_loss_epoch=557.0, valid_loss=2.27e+7]
Epoch 74:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=3.2e+3, train_loss_epoch=2.24e+3, valid_loss=2.27e+7]
Epoch 76:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=4.02e+3, train_loss_epoch=2.41e+3, valid_loss=2.27e+7]
Epoch 78:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=3.82e+3, train_loss_epoch=2.15e+3, valid_loss=2.27e+7]
Epoch 79:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=813.0, train_loss_epoch=701.0, valid_loss=2.27e+7]
Epoch 81:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=974.0, train_loss_epoch=1.09e+3, valid_loss=2.27e+7]
Epoch 83:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=977.0, train_loss_epoch=761.0, valid_loss=2.27e+7]
Epoch 85:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.95e+3, train_loss_epoch=1.89e+3, valid_loss=2.27e+7]
Epoch 86:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=894.0, train_loss_epoch=541.0, valid_loss=2.27e+7]
Epoch 87:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=74.00, train_loss_epoch=108.0, valid_loss=2.27e+7]
Epoch 89:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=957.0, train_loss_epoch=819.0, valid_loss=2.27e+7]
Epoch 91:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.53e+3, train_loss_epoch=1.49e+3, valid_loss=2.27e+7]
Epoch 94:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=244.0, train_loss_epoch=1.16e+3, valid_loss=2.27e+7]
Epoch 97:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.01e+3, train_loss_epoch=1.27e+3, valid_loss=2.27e+7]
Epoch 99:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.11e+3, train_loss_epoch=663.0, valid_loss=2.27e+7]
Epoch 99: 100%|██████████| 2/2 [00:00<00:00, 50.24it/s, v_num=0, train_loss_step=429.0, train_loss_epoch=663.0, valid_loss=2.27e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 2/2 [00:00<00:00, 156.19it/s]
Epoch 101:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.1e+3, train_loss_epoch=1.08e+3, valid_loss=2.36e+7]
Epoch 104:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=3.370, train_loss_epoch=344.0, valid_loss=2.36e+7]
Epoch 106: 100%|██████████| 2/2 [00:00<00:00, 51.60it/s, v_num=0, train_loss_step=1.42e+3, train_loss_epoch=990.0, valid_loss=2.36e+7]
Epoch 107:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.74e+3, train_loss_epoch=1.47e+3, valid_loss=2.36e+7]
Epoch 109:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=74.40, train_loss_epoch=968.0, valid_loss=2.36e+7]
Epoch 111:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=425.0, train_loss_epoch=866.0, valid_loss=2.36e+7]
Epoch 114:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=3.83e+3, train_loss_epoch=2.01e+3, valid_loss=2.36e+7]
Epoch 116:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=27.10, train_loss_epoch=819.0, valid_loss=2.36e+7]
Epoch 119:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.7e+3, train_loss_epoch=1.85e+3, valid_loss=2.36e+7]
Epoch 122:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=50.70, train_loss_epoch=1.01e+3, valid_loss=2.36e+7]
Epoch 125:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=6.05e+3, train_loss_epoch=3.3e+3, valid_loss=2.36e+7]
Epoch 127:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=70.90, train_loss_epoch=774.0, valid_loss=2.36e+7]
Epoch 127: 100%|██████████| 2/2 [00:00<00:00, 48.32it/s, v_num=0, train_loss_step=70.90, train_loss_epoch=774.0, valid_loss=2.36e+7]
Epoch 130:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=360.0, train_loss_epoch=482.0, valid_loss=2.36e+7]
Epoch 132:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=3.63e+3, train_loss_epoch=1.88e+3, valid_loss=2.36e+7]
Epoch 135:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.05e+3, train_loss_epoch=984.0, valid_loss=2.36e+7]
Epoch 137:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2e+3, train_loss_epoch=1.37e+3, valid_loss=2.36e+7]
Epoch 139:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.44e+3, train_loss_epoch=1.33e+3, valid_loss=2.36e+7]
Epoch 139: 100%|██████████| 2/2 [00:00<00:00, 49.27it/s, v_num=0, train_loss_step=1.06e+3, train_loss_epoch=651.0, valid_loss=2.36e+7]
Epoch 140:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.06e+3, train_loss_epoch=651.0, valid_loss=2.36e+7]
Epoch 142:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.11e+3, train_loss_epoch=809.0, valid_loss=2.36e+7]
Epoch 145:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=371.0, train_loss_epoch=824.0, valid_loss=2.36e+7]
Epoch 148:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=5.090, train_loss_epoch=164.0, valid_loss=2.36e+7]
Epoch 149: 100%|██████████| 2/2 [00:00<00:00, 57.70it/s, v_num=0, train_loss_step=227.0, train_loss_epoch=839.0, valid_loss=2.36e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 2/2 [00:00<00:00, 167.27it/s]
Epoch 150:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=227.0, train_loss_epoch=729.0, valid_loss=2.47e+7]
Epoch 152:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=998.0, train_loss_epoch=1.5e+3, valid_loss=2.47e+7]
Epoch 155:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.38e+3, train_loss_epoch=1.26e+3, valid_loss=2.47e+7]
Epoch 158:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.13e+3, train_loss_epoch=1.89e+3, valid_loss=2.47e+7]
Epoch 160:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.18e+3, train_loss_epoch=1.19e+3, valid_loss=2.47e+7]
Epoch 163:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=181.0, train_loss_epoch=986.0, valid_loss=2.47e+7]
Epoch 165:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.11e+3, train_loss_epoch=1.04e+3, valid_loss=2.47e+7]
Epoch 168:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.04e+3, train_loss_epoch=1.44e+3, valid_loss=2.47e+7]
Epoch 171:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=145.0, train_loss_epoch=439.0, valid_loss=2.47e+7]
Epoch 174:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.01e+3, train_loss_epoch=1.36e+3, valid_loss=2.47e+7]
Epoch 176:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=4.67e+3, train_loss_epoch=2.76e+3, valid_loss=2.47e+7]
Epoch 179:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=19.20, train_loss_epoch=924.0, valid_loss=2.47e+7]
Epoch 182:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=933.0, train_loss_epoch=1.01e+3, valid_loss=2.47e+7]
Epoch 184:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.73e+3, train_loss_epoch=1.64e+3, valid_loss=2.47e+7]
Epoch 186:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=4.18e+3, train_loss_epoch=2.52e+3, valid_loss=2.47e+7]
Epoch 189:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=890.0, train_loss_epoch=1.04e+3, valid_loss=2.47e+7]
Epoch 192:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.24e+3, train_loss_epoch=718.0, valid_loss=2.47e+7]
Epoch 194:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.59e+3, train_loss_epoch=1.35e+3, valid_loss=2.47e+7]
Epoch 197:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=754.0, train_loss_epoch=419.0, valid_loss=2.47e+7]
Epoch 199: 100%|██████████| 2/2 [00:00<00:00, 58.51it/s, v_num=0, train_loss_step=371.0, train_loss_epoch=1.13e+3, valid_loss=2.47e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
(_train_tune pid=8182)
Validation DataLoader 0: 100%|██████████| 2/2 [00:00<00:00, 122.48it/s]
(_train_tune pid=8182)
Epoch 202:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=181.0, train_loss_epoch=1.14e+3, valid_loss=2.29e+7]
Epoch 205:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=378.0, train_loss_epoch=502.0, valid_loss=2.29e+7]
Epoch 208:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.47e+3, train_loss_epoch=984.0, valid_loss=2.29e+7]
Epoch 210:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=136.0, train_loss_epoch=724.0, valid_loss=2.29e+7]
Epoch 213:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=396.0, train_loss_epoch=666.0, valid_loss=2.29e+7]
Epoch 215:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=806.0, train_loss_epoch=1.14e+3, valid_loss=2.29e+7]
Epoch 218:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.08e+3, train_loss_epoch=1.27e+3, valid_loss=2.29e+7]
Epoch 220:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=531.0, train_loss_epoch=530.0, valid_loss=2.29e+7]
Epoch 223:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=14.00, train_loss_epoch=1.18e+3, valid_loss=2.29e+7]
Epoch 226:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.23e+3, train_loss_epoch=1.38e+3, valid_loss=2.29e+7]
Epoch 228:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=352.0, train_loss_epoch=911.0, valid_loss=2.29e+7]
Epoch 231:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=58.90, train_loss_epoch=1.01e+3, valid_loss=2.29e+7]
Epoch 233: 100%|██████████| 2/2 [00:00<00:00, 56.29it/s, v_num=0, train_loss_step=470.0, train_loss_epoch=1.14e+3, valid_loss=2.29e+7]
Epoch 234:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=470.0, train_loss_epoch=1.14e+3, valid_loss=2.29e+7]
Epoch 236:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=246.0, train_loss_epoch=754.0, valid_loss=2.29e+7]
Epoch 238:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=469.0, train_loss_epoch=663.0, valid_loss=2.29e+7]
Epoch 241:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.3e+3, train_loss_epoch=1.47e+3, valid_loss=2.29e+7]
Epoch 244:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=67.90, train_loss_epoch=813.0, valid_loss=2.29e+7]
Epoch 246:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.74e+3, train_loss_epoch=1.4e+3, valid_loss=2.29e+7]
Epoch 249:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=316.0, train_loss_epoch=1.1e+3, valid_loss=2.29e+7]
Epoch 249: 100%|██████████| 2/2 [00:00<00:00, 43.66it/s, v_num=0, train_loss_step=204.0, train_loss_epoch=1.1e+3, valid_loss=2.29e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 2/2 [00:00<00:00, 125.55it/s]
Epoch 251:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.59e+3, train_loss_epoch=1.28e+3, valid_loss=2.31e+7]
Epoch 253:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=171.0, train_loss_epoch=1.07e+3, valid_loss=2.31e+7]
Epoch 256:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=860.0, train_loss_epoch=706.0, valid_loss=2.31e+7]
Epoch 258: 100%|██████████| 2/2 [00:00<00:00, 53.94it/s, v_num=0, train_loss_step=131.0, train_loss_epoch=1.17e+3, valid_loss=2.31e+7]
Epoch 258: 100%|██████████| 2/2 [00:00<00:00, 51.47it/s, v_num=0, train_loss_step=131.0, train_loss_epoch=960.0, valid_loss=2.31e+7]
Epoch 259:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=131.0, train_loss_epoch=960.0, valid_loss=2.31e+7]
Epoch 261:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=4.08e+3, train_loss_epoch=2.22e+3, valid_loss=2.31e+7]
Epoch 263: 100%|██████████| 2/2 [00:00<00:00, 54.38it/s, v_num=0, train_loss_step=1.28e+3, train_loss_epoch=1.24e+3, valid_loss=2.31e+7]
Epoch 264:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.28e+3, train_loss_epoch=1.24e+3, valid_loss=2.31e+7]
Epoch 266:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=721.0, train_loss_epoch=967.0, valid_loss=2.31e+7]
Epoch 269:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=1.45e+3, train_loss_epoch=820.0, valid_loss=2.31e+7]
Epoch 271:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=178.0, train_loss_epoch=1.03e+3, valid_loss=2.31e+7]
Epoch 274:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=171.0, train_loss_epoch=1.28e+3, valid_loss=2.31e+7]
Epoch 276:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=3.95e+3, train_loss_epoch=2.11e+3, valid_loss=2.31e+7]
Epoch 276: 100%|██████████| 2/2 [00:00<00:00, 44.91it/s, v_num=0, train_loss_step=3.95e+3, train_loss_epoch=2.11e+3, valid_loss=2.31e+7]
Epoch 276: 100%|██████████| 2/2 [00:00<00:00, 44.44it/s, v_num=0, train_loss_step=2.17e+3, train_loss_epoch=2.11e+3, valid_loss=2.31e+7]
Epoch 277:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.17e+3, train_loss_epoch=1.65e+3, valid_loss=2.31e+7]
Epoch 279:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=61.40, train_loss_epoch=992.0, valid_loss=2.31e+7]
Epoch 282:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=134.0, train_loss_epoch=496.0, valid_loss=2.31e+7]
Epoch 284:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=432.0, train_loss_epoch=314.0, valid_loss=2.31e+7]
Epoch 287:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=758.0, train_loss_epoch=1.38e+3, valid_loss=2.31e+7]
Epoch 289:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=264.0, train_loss_epoch=727.0, valid_loss=2.31e+7]
Epoch 292:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=16.00, train_loss_epoch=650.0, valid_loss=2.31e+7]
Epoch 294:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.89e+3, train_loss_epoch=1.74e+3, valid_loss=2.31e+7]
Epoch 297:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=876.0, train_loss_epoch=1.1e+3, valid_loss=2.31e+7]
Epoch 299: 100%|██████████| 2/2 [00:00<00:00, 57.64it/s, v_num=0, train_loss_step=83.70, train_loss_epoch=1.11e+3, valid_loss=2.31e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
(_train_tune pid=8182)
Validation DataLoader 0: 100%|██████████| 2/2 [00:00<00:00, 109.29it/s]
Epoch 301:   0%|          | 0/2 [00:00<?, ?it/s, v_num=0, train_loss_step=2.14e+3, train_loss_epoch=1.37e+3, valid_loss=2.13e+7]

(_train_tune pid=8182) `Trainer.fit` stopped: `max_steps=5000` reached.
2026-05-21 09:37:44,286	INFO tune.py:1001 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/_train_tune_2026-05-21_09-24-47' in 0.0151s.
INFO:lightning_fabric.utilities.seed:Seed set to 11

Epoch 2499: 100%|██████████| 2/2 [00:00<00:00, 36.27it/s, v_num=0, train_loss_step=70.80, train_loss_epoch=943.0, valid_loss=1.98e+7]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 2/2 [00:00<00:00, 113.09it/s]
Epoch 2499: 100%|██████████| 2/2 [00:00<00:00, 21.75it/s, v_num=0, train_loss_step=70.80, train_loss_epoch=1.21e+3, valid_loss=1.91e+7]
Epoch 2499: 100%|██████████| 2/2 [00:00<00:00, 20.84it/s, v_num=0, train_loss_step=70.80, train_loss_epoch=1.21e+3, valid_loss=1.91e+7]

INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:pytorch_lightning.callbacks.model_summary:
  | Name         | Type              | Params | Mode
-----------------------------------------------------------
0 | loss         | MAE               | 0      | eval
1 | padder_train | ConstantPad1d     | 0      | train
2 | scaler       | TemporalNorm      | 0      | train
3 | model        | PatchTST_backbone | 400 K  | train
-----------------------------------------------------------
400 K     Trainable params
3         Non-trainable params
400 K     Total params
1.603     Total estimated model params size (MB)
89        Modules in train mode
1         Modules in eval mode

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

INFO:pytorch_lightning.utilities.rank_zero:`Trainer.fit` stopped: `max_steps=1000` reached.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: True (cuda), used: True
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

In [11]:
# ----------------------------------------------------------------------
# 6. Вывод результатов
# ----------------------------------------------------------------------
print("\n" + "="*60)
print("СРАВНЕНИЕ СЦЕНАРИЕВ (медианные метрики)")
print("="*60)
results_df = pd.DataFrame({
    'Baseline (AutoARIMA)': baseline_metrics,
    'Сценарий 1 (двухсегментный)': s1_metrics,
    'Сценарий 2 (полный конвейер)': s2_metrics
}).T
print(results_df.round(4))

print("\n" + "="*60)
print("ВРЕМЯ ОБУЧЕНИЯ")
print("="*60)
print(f"Baseline (AutoARIMA на всех рядах):        {baseline_time:.2f} сек")
print(f"Сценарий 1 (SESOptimized + AutoARIMA):     {s1_total_time:.2f} сек")
print(f"  - SESOptimized на Smooth+Erratic:        {s1_times[0]:.2f} сек")
print(f"  - AutoARIMA на Intermittent+Lumpy:       {s1_times[1]:.2f} сек")
print(f"Сценарий 2 (индивидуальные чемпионы):      {s2_total_time:.2f} сек")
for cls, t in s2_times.items():
    print(f"  - {cls}: {t:.2f} сек")

============================================================
СРАВНЕНИЕ СЦЕНАРИЕВ (медианные метрики)
============================================================
                                mase   rmsse   smape
Baseline (AutoARIMA)          0.2900  0.2647  0.1021
Сценарий 1 (двухсегментный)   0.2234  0.2280  0.0929
Сценарий 2 (полный конвейер)  0.1997  0.2022  0.0873

============================================================
ВРЕМЯ ОБУЧЕНИЯ
============================================================
Baseline (AutoARIMA на всех рядах):        359.89 сек
Сценарий 1 (SESOptimized + AutoARIMA):     173.65 сек
  - SESOptimized на Smooth+Erratic:        2.41 сек
  - AutoARIMA на Intermittent+Lumpy:       171.24 сек
Сценарий 2 (индивидуальные чемпионы):      1010.17 сек
  - Smooth: 12.42 сек
  - Erratic: 805.72 сек
  - Intermittent: 141.66 сек
  - Lumpy: 50.37 сек

In [12]:
# ----------------------------------------------------------------------
# 7. Дополнительно: качество по классам для каждого сценария
# ----------------------------------------------------------------------
def metrics_by_class(forecast_df, classification_df, train_all):
    class_metrics = {}
    for class_name in classification_df['class'].unique():
        ids = classification_df[classification_df['class']==class_name]['unique_id'].values
        sub = forecast_df[forecast_df['unique_id'].isin(ids)]
        if len(sub) == 0:
            continue
        class_metrics[class_name] = evaluate_forecast(sub, train_all, 'forecast')
    return pd.DataFrame(class_metrics).T

print("\n" + "="*60)
print("МЕТРИКИ ПО КЛАССАМ ДЛЯ СЦЕНАРИЯ 2")
print("="*60)
metrics_class_s2 = metrics_by_class(s2_forecast, classification_df, train_all)
print(metrics_class_s2.round(4))

# Сохраняем результаты
results_df.to_csv('scenarios_comparison.csv')
print("\nРезультаты сохранены в 'scenarios_comparison.csv'")

============================================================
МЕТРИКИ ПО КЛАССАМ ДЛЯ СЦЕНАРИЯ 2
============================================================
                mase   rmsse   smape
Smooth        0.5391  0.5485  0.1015
Erratic       0.1447  0.1466  0.2041
Intermittent  0.0000  0.0000  0.0000
Lumpy         0.0465  0.0481  0.4752

Результаты сохранены в 'scenarios_comparison.csv'

In [13]:
print("\n" + "="*60)
print("МЕТРИКИ ПО КЛАССАМ ДЛЯ СЦЕНАРИЯ 1")
print("="*60)
metrics_class_s1 = metrics_by_class(s1_forecast, classification_df, train_all)
print(metrics_class_s1.round(4))

============================================================
МЕТРИКИ ПО КЛАССАМ ДЛЯ СЦЕНАРИЯ 1
============================================================
                mase   rmsse   smape
Smooth        0.5915  0.5719  0.1057
Erratic       0.2129  0.1834  0.2262
Intermittent  0.0000  0.0000  0.0000
Lumpy         0.0465  0.0481  0.4752

In [15]:
# Сохраняем результаты прогнозов
s1_forecast.to_csv('s1_forecast.csv')
s2_forecast.to_csv('s2_forecast.csv')
print("\nРезультаты сохранены")

Результаты сохранены